=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/landmarks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/landmarks"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:lm="http://mars-sim.sourceforge.net/landmarks">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="landmark-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="lm:landmark" minOccurs="0" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="landmark">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="longitude" type="lm:angle"></xs:attribute>
    		<xs:attribute name="latitude" type="lm:angle"></xs:attribute>
    		<xs:attribute name="diameter" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:simpleType name="angle">
    	<xs:restriction base="xs:string">
    		<xs:pattern value="\d{1,3}\.\d (N|S|E|W)"></xs:pattern>
    	</xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/landmarks.xml
<?xml version="1.0" encoding="utf-8"?>
  <!--Landmark coordinates from USGS Astrogeology Research Program-->
  <!--http://planetarynames.wr.usgs.gov/SearchResults?target=MARS-->
  <!--Landmarks to be displayed in the user interface. -->
  <landmark-list xmlns="http://mars-sim.sourceforge.net/landmarks" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mars-sim.sourceforge.net/landmarks schema/landmarks.xsd">
  	<landmark approvaldate="1973" diameter="1817.66" latitude="10.79 N" longitude="114.49 W" name="Lunae Planum" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1350.65" latitude="40.4 N" longitude="163.71 E" name="Phlegra Montes" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1044" latitude="24.08 N" longitude="146.14 E" name="Elysium Fossae" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1757.67" latitude="10.29 N" longitude="154.39 W" name="Ares Vallis" origin="Word for 'Mars' in Greek."/>
  	<landmark approvaldate="1973" diameter="1580" latitude="25.14 N" longitude="117.12 W" name="Kasei Valles" origin="Word for &quot;Mars&quot; in Japanese."/>
  	<landmark approvaldate="1973" diameter="2731.21" latitude="35.57 S" longitude="17.26 W" name="Sirenum Fossae" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="2299.16" latitude="42.43 S" longitude="70.5 E" name="Hellas Planitia" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1142.58" latitude="37.57 S" longitude="136.79 W" name="Nereidum Montes" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="2030.64" latitude="27.89 S" longitude="75.76 W" name="Claritas Fossae" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="3560.45" latitude="46.74 N" longitude="117.52 E" name="Utopia Planitia" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1305.69" latitude="12.15 S" longitude="140.83 W" name="Eos Chasma" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1471.56" latitude="8.27 S" longitude="137.93 W" name="Capri Chasma" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1811.23" latitude="26.4 S" longitude="90.33 W" name="Solis Planum" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="3761.28" latitude="14.01 S" longitude="121.41 W" name="Valles Marineris" origin="General name of the system of canyons honoring the scientific team of the Mariner 9 program."/>
  	<landmark approvaldate="1973" diameter="2002.91" latitude="87.73 N" longitude="32.53 E" name="Vastitas Borealis" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1190.31" latitude="6.36 S" longitude="78.81 W" name="Noctis Labyrinthus" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="3000.79" latitude="2.98 N" longitude="154.74 E" name="Elysium Planitia" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1166.63" latitude="27 N" longitude="69.85 W" name="Ceraunius Fossae" origin="Classical albedo feature name"/>
  	<landmark approvaldate="1973" diameter="1601.73" latitude="21.42 S" longitude="109.89 E" name="Hesperia Planum" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1542.44" latitude="28.43 N" longitude="139.69 W" name="Chryse Planitia" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1214.86" latitude="9.2 N" longitude="67.1 E" name="Syrtis Major Planum" origin="Albedo feature name; changed from Planitia to Planum."/>
  	<landmark approvaldate="1973" diameter="1871.97" latitude="47.19 N" longitude="4.31 W" name="Arcadia Planitia" origin="From classical albedo feature at 45N, 120W."/>
  	<landmark approvaldate="1973" diameter="2809.04" latitude="25.75 N" longitude="17.09 W" name="Amazonis Planitia" origin="Classical albedo feature name; home of the Amazons."/>
  	<landmark approvaldate="1973" diameter="2058.91" latitude="1.57 N" longitude="67.42 W" name="Tharsis Montes" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1033.97" latitude="43.87 N" longitude="48.86 E" name="Protonilus Mensae" origin="From albedo feature at 42N, 315W."/>
  	<landmark approvaldate="1973" diameter="1720" latitude="16.23 N" longitude="145.14 W" name="Tiu Valles" origin="Word for &quot;Mars&quot; in old English (West Germanic)."/>
  	<landmark approvaldate="1973" diameter="2116.24" latitude="40.42 N" longitude="108.6 W" name="Tempe Fossae" origin="From albedo feature at 40N, 70W."/>
  	<landmark approvaldate="1973" diameter="2361.86" latitude="49.83 N" longitude="83.91 W" name="Tantalus Fossae" origin="From albedo feature at 35N, 110W."/>
  	<landmark approvaldate="1973" diameter="3362.97" latitude="49.76 N" longitude="159.26 W" name="Acidalia Planitia" origin="From classical albedo feature at 44N, 21W."/>
  	<landmark approvaldate="1973" diameter="2072.02" latitude="49.39 N" longitude="73.18 W" name="Alba Fossae" origin="Classical albedo name."/>
  	<landmark approvaldate="1973" diameter="1907.94" latitude="44.34 N" longitude="103.88 W" name="Mareotis Fossae" origin="From albedo feature at 32N, 96W."/>
  	<landmark approvaldate="1973" diameter="1224.58" latitude="13.94 N" longitude="88.38 E" name="Isidis Planitia" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1973" diameter="1029" latitude="7.33 N" longitude="137.91 W" name="Shalbatana Vallis" origin="Word for &quot;Mars&quot; in Akkadian."/>
  	<landmark approvaldate="1973" diameter="1585.28" latitude="23.63 S" longitude="26.18 W" name="Memnonia Fossae" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1976" diameter="2176.23" latitude="9.19 N" longitude="119.42 E" name="Nepenthes Mensae" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1976" diameter="1350.61" latitude="28.14 N" longitude="35.53 W" name="Lycus Sulci" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1976" diameter="1020" latitude="40.65 N" longitude="17.94 E" name="Mamers Valles" origin="Word for &quot;Mars&quot; in Oscan."/>
  	<landmark approvaldate="1976" diameter="1429.87" latitude="83.35 S" longitude="157.7 E" name="Planum Australe" origin="Classical albedo feature."/>
  	<landmark approvaldate="1976" diameter="1914.77" latitude="18.4 N" longitude="46.44 W" name="Olympus Rupes" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1976" diameter="1379.21" latitude="75.54 S" longitude="90.24 E" name="Promethei Rupes" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="3244.3" latitude="64.37 S" longitude="97 E" name="Promethei Terra" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="3635.18" latitude="39.49 S" longitude="25.85 W" name="Terra Sirenum" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="1867.65" latitude="1.6 N" longitude="131.95 W" name="Xanthe Terra" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="3873.48" latitude="60.2 S" longitude="82.95 W" name="Aonia Terra" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="5519.45" latitude="50.41 S" longitude="174.84 W" name="Noachis Terra" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="1515" latitude="10.23 N" longitude="121.62 W" name="Maja Valles" origin="Nepali word for &quot;Mars&quot;."/>
  	<landmark approvaldate="1979" diameter="1954.94" latitude="38.69 N" longitude="109.39 W" name="Tempe Terra" origin="From albedo feature at 40N, 70W."/>
  	<landmark approvaldate="1979" diameter="1043.63" latitude="1.44 N" longitude="88.23 E" name="Libya Montes" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="4688.44" latitude="2.72 N" longitude="51.3 E" name="Terra Sabaea" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="5855.87" latitude="32.68 S" longitude="147.75 E" name="Terra Cimmeria" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="4851.74" latitude="21.25 N" longitude="5.72 E" name="Arabia Terra" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="1017.66" latitude="52.61 S" longitude="141.79 E" name="Eridania Scopulus" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="1051.94" latitude="42.14 S" longitude="104.95 E" name="Reull Vallis" origin="Word for &quot;planet&quot; in Gaelic."/>
  	<landmark approvaldate="1979" diameter="2733.22" latitude="1.85 S" longitude="155.08 W" name="Margaritifer Terra" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1979" diameter="2470.14" latitude="11.9 S" longitude="88.84 E" name="Tyrrhena Terra" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1982" diameter="1922.02" latitude="18.35 S" longitude="54.05 W" name="Daedalia Planum" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1982" diameter="1425" latitude="6.62 S" longitude="77.11 E" name="Oenotria Scopuli" origin="Classical albedo feature name."/>
  	<landmark approvaldate="1985" diameter="1521.68" latitude="65.47 N" longitude="40.87 W" name="Scandia Colles" origin="From albedo feature name."/>
  	<landmark approvaldate="1985" diameter="1550.81" latitude="52.53 N" longitude="112.21 E" name="Cydnus RupÄ“s" origin="From albedo feature at 70N, 248W."/>
  	<landmark approvaldate="1985" diameter="1496.36" latitude="24.58 N" longitude="95.47 W" name="Labeatis Fossae" origin="Previously named feature at 30N, 75W; expanded coordinates."/>
