=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/malfunctions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/malfunctions"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:mal="http://mars-sim.sourceforge.net/malfunctions">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="malfunction-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="mal:malfunction" minOccurs="0" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="malfunction">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="mal:severity"></xs:element>
    			<xs:element ref="mal:probability"></xs:element>
    			<xs:element ref="mal:repair-time" minOccurs="0"></xs:element>
    			<xs:element ref="mal:emergency-repair-time" minOccurs="0"></xs:element>
    			<xs:element ref="mal:eva-repair-time" minOccurs="0"></xs:element>
    			<xs:element ref="mal:entity-list"></xs:element>
    			<xs:element ref="mal:effect-list" minOccurs="0"></xs:element>
    			<xs:element ref="mal:medical-complaint-list" minOccurs="0"></xs:element>
    			<xs:element ref="mal:repair-parts-list" minOccurs="0"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="severity">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="probability">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="repair-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="emergency-repair-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="eva-repair-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="entity-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="mal:entity" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="entity">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="effect-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="mal:effect" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="effect">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="type">
    			<xs:simpleType>
   					<xs:restriction base="xs:string">
   						<xs:enumeration value="resource"></xs:enumeration>
   						<xs:enumeration value="life-support"></xs:enumeration>
   					</xs:restriction>
   				</xs:simpleType>
    		</xs:attribute>
    		<xs:attribute name="change-rate" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="medical-complaint-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="mal:medical-complaint" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="medical-complaint">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="probability" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="repair-parts-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="mal:part" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="part">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="number" type="xs:integer"></xs:attribute>
    		<xs:attribute name="probability" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/malfunctions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- List of possible malfunctions -->
<malfunction-list
	xmlns="http://mars-sim.sourceforge.net/malfunctions"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mars-sim.sourceforge.net/malfunctions schema/malfunctions.xsd">

	<!-- Small air leak -->
	<malfunction name="Air Leak">
		
		<!-- Relative severity of the malfunction. (required) -->
		<!-- Values: 1 to 100 (100 = most severe) -->
		<severity value="100" />
		
		<!-- Relative probability of this malfunction occurring. (required) -->
		<!-- Values: 0.0 to 100.0 (100.0 = most likely) -->
		<probability value="10.0" />
		
		<!-- Normal (non-EVA) repair time to fix. (millisols) (optional) -->
		<repair-time value="100.0" />
		
		<!-- Emergency repair time to fix. (millisols) (optional) -->
		<emergency-repair-time value="10.0" />
		
		<!-- EVA repair time to fix. (millisols) (optional) -->
		<eva-repair-time value="0.0" />
		
		<!-- List of entities that are susceptible to this malfunction. (min 1 entity required) -->
		<entity-list>
			<entity name="life support" />
			<entity name="rover" />
			<entity name="eva suit" />
		</entity-list>
		
		<!-- List of effects this malfunction can produce. (optional) -->
		<effect-list>
		
			<!-- Resource effects have a change rate for a given resource in inventory. -->
			<!-- Values: Change rate of resource in inventory. (kg/millisol) -->
			<!-- See resources.txt -->
			<effect type="resource" name="Oxygen" change-rate="-.1" />
			
			<!-- Life support effects have a change rate in life support provided. -->
			<!-- Values: Change rate of life support. (kg/millisol) -->
			<!-- See resources.txt -->
			<effect type="life-support" name="Oxygen" change-rate="-.01" />
			
			<!-- Life support effects have a change rate in life support provided. -->
			<!-- Values: Change rate of life support. (atm/millisol) -->
			<effect type="life-support" name="Air Pressure" change-rate="-.01" />
		</effect-list>
		
		<!-- List of medical injuries that can be immediately caused by this malfunction. (optional) -->
        <!-- See medical complaint list in medical.xml. -->
		<medical-complaint-list>
		</medical-complaint-list>
		
		<!-- Repair parts required to fix this malfunction. (optional) -->
		<!-- See parts.xml -->
		<repair-parts-list>
			<!-- A part required for repairing this malfunction. -->
			<!-- Values: number - the number of the part needed. -->
			<!-- Values: probability - the percentage probability that the part will be needed for repair. -->
			<part name="airleak patch" number="1" probability="60" />
		</repair-parts-list>
		
	</malfunction>
	
	<!-- Small electrical or chemical fire. -->
	<malfunction name="Minor Fire">
		<severity value="60" />
		<probability value="15.0" />
		<repair-time value="100.0" />
		<emergency-repair-time value="10.0" />
		<entity-list>
			<entity name="life support" />
			<entity name="rover" />
			<entity name="eva suit" />	
		</entity-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="co2 extinguisher" number="1" probability="50" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Medium electrical or chemical fire. -->
	<malfunction name="Fire">
		<severity value="80" />
		<probability value="5" />
		<repair-time value="200.0" />
		<emergency-repair-time value="20.0" />
		<entity-list>
			<entity name="life support" />
			<entity name="rover" />
		</entity-list>
		<effect-list>
			<effect type="life-support" name="Oxygen" change-rate="-.01" />
			<effect type="life-support" name="Temperature" change-rate="+.01" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" probability="15.0" />
			<medical-complaint name="Burns" probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="co2 extinguisher" number="1" probability="50" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Large electrical or chemical fire. -->
	<malfunction name="Major Fire">
		<severity value="100" />
		<probability value="1" />
		<repair-time value="400.0" />
		<emergency-repair-time value="40.0" />
		<entity-list>
			<entity name="life support" />
		</entity-list>
		<effect-list>
			<effect type="life-support" name="Oxygen" change-rate="-.02" />
			<effect type="life-support" name="Temperature" change-rate="+.02" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" probability="30.0" />
			<medical-complaint name="Burns" probability="15.0" />
			<medical-complaint name="Major Burns" probability="5.0" />
		</medical-complaint-list>
		<repair-parts-list>
			<part name="co2 extinguisher" number="2" probability="50" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Damaged wheel on rover. -->
	<malfunction name="Damaged Wheel">
		<severity value="20" />
		<probability value="30.0" />
		<eva-repair-time value="50.0" />
		<entity-list>
			<entity name="rover" />
		</entity-list>
		<repair-parts-list>
			<part name="rover wheel" number="1" probability="60" />
		</repair-parts-list>
	</malfunction>

	<!-- Methane fuel leak. -->
	<malfunction name="Fuel Leak">
		<severity value="50" />
		<probability value="30.0" />
		<emergency-repair-time value="100.0" />
		<eva-repair-time value="50.0" />
		<entity-list>
			<entity name="rover" />
		</entity-list>
		<effect-list>
			<effect type="resource" name="Methane" change-rate="-.1" />
		</effect-list>
		<repair-parts-list>
			<part name="gasket" number="1" probability="30" />
			<part name="valve" number="1" probability="20" />
			<part name="epoxy resin bottle" number="1" probability="50" />
			<part name="plastic tubing" number="1" probability="10" />
		</repair-parts-list>
	</malfunction>

	<!-- Problems with the rover's generator. -->
	<malfunction name="Generator Problems">
		<severity value="50" />
		<probability value="40.0" />
		<repair-time value="50.0" />
		<emergency-repair-time value="50.0" />
		<entity-list>
			<entity name="rover" />
		</entity-list>
		<repair-parts-list>
			<part name="gasket" number="1" probability="20" />
			<part name="spark plug" number="1" probability="15" />
			<part name="coolant bottle" number="1" probability="40" />
			<part name="electrical wire" number="2" probability="20" />
			<part name="wire connector" number="2" probability="20" />
			<part name="plastic tubing" number="1" probability="10" />
			<part name="lubricant bottle" number="1" probability="30" />
			<part name="timing belt" number="1" probability="30" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Battery failure. -->
	<malfunction name="Battery Failure">
		<severity value="40" />
		<probability value="25.0" />
		<repair-time value="50.0" />
		<entity-list>
			<entity name="rover" />
			<entity name="light utility vehicle" />
		</entity-list>
		<repair-parts-list>
			<part name="wire connector" number="2" probability="30" />
			<part name="electrical wire" number="2" probability="40" />
			<part name="rover battery" number="1" probability="10" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Communication system failure. -->
	<malfunction name="Communication System Failure">
		<severity value="20" />
		<probability value="10.0" />
		<repair-time value="50.0" />
		<eva-repair-time value="50.0" />
		<entity-list>
			<entity name="rover" />
			<entity name="communication" />
		</entity-list>
		<repair-parts-list>
			<part name="wire connector" number="2" probability="30" />
			<part name="electrical wire" number="2" probability="40" />
			<part name="radio antenna" number="1" probability="10" />
			<part name="satellite dish" number="1" probability="5" />
			<part name="communications circuit board" number="1" probability="5" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Navigation system failure. -->
	<malfunction name="Navigation System Failure">
		<severity value="15" />
		<probability value="7.0" />
		<repair-time value="50.0" />
		<eva-repair-time value="20.0" />
		<entity-list>
			<entity name="rover" />
		</entity-list>
		<repair-parts-list>
			<part name="wire connector" number="2" probability="30" />
			<part name="electrical wire" number="2" probability="40" />
			<part name="satellite dish" number="1" probability="10" />
			<part name="navigation circuit board" number="1" probability="5" />
		</repair-parts-list>
	</malfunction>
	
	<malfunction name="Control Panel Malfunction">
		<severity value="35" />
		<probability value="2.0" />
		<repair-time value="100.0" />
		<entity-list>
			<entity name="rover" />
			<entity name="light utility vehicle" />
		</entity-list>
		<repair-parts-list>
			<part name="wire connector" number="2" probability="30" />
			<part name="electrical wire" number="2" probability="40" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Leak in the water reserves. -->
	<malfunction name="Water Leak">
		<severity value="50" />
		<probability value="10.0" />
		<emergency-repair-time value="100.0" />
		<entity-list>
			<entity name="rover" />
			<entity name="living accomodations" />
			<entity name="farming" />
			<entity name="manufacture" />
			<entity name="eva suit" />
			<entity name="areothermal power source" />
		</entity-list>
		<effect-list>
			<effect type="resource" name="Water" change-rate="-.1" />
		</effect-list>
		<repair-parts-list>
			<part name="gasket" number="1" probability="30" />
			<part name="valve" number="1" probability="20" />
			<part name="plastic tubing" number="2" probability="20" />
			<part name="epoxy resin bottle" number="1" probability="50" />
			<part name="copper pipe" number="1" probability="10" />
		</repair-parts-list>
	</malfunction>
	
	<!-- Failure of life support heating unit.  -->
	<malfunction name="Heating Unit Failure">
		<severity value="70" />
		<probability value="10.0" />
		<repair-time value="100.0" />
		<emergency-repair-time value="20.0" />
		<entity-list>
			<entity name="eva suit" />
		</entity-list>
