=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/minerals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/minerals"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:min="http://mars-sim.sourceforge.net/minerals">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="mineral-concentrations">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="min:mineral" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="mineral">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="min:locale-list"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="frequency">
    			<xs:simpleType>
   					<xs:restriction base="xs:string">
   						<xs:enumeration value="common"></xs:enumeration>
   						<xs:enumeration value="uncommon"></xs:enumeration>
   						<xs:enumeration value="rare"></xs:enumeration>
   						<xs:enumeration value="very_rare"></xs:enumeration>
   					</xs:restriction>
   				</xs:simpleType>
    		</xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="locale-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="min:locale" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="locale">
    	<xs:complexType>
    		<xs:attribute name="name">
    			<xs:simpleType>
   					<xs:restriction base="xs:string">
   						<xs:enumeration value="volcanic"></xs:enumeration>
   						<xs:enumeration value="sedimentary"></xs:enumeration>
   						<xs:enumeration value="crater"></xs:enumeration>
   					</xs:restriction>
   				</xs:simpleType>
    		</xs:attribute>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/minerals.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- List of all mineral concentrations that can be mined. -->
<mineral-concentrations
	xmlns="http://mars-sim.sourceforge.net/minerals"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mars-sim.sourceforge.net/minerals schema/minerals.xsd">

	<!-- Hematite is an iron ore. -->
	<!-- http://en.wikipedia.org/wiki/Hematite -->
	<!-- frequency - how common are the mineral concentrations? -->
	<!-- Valid values: "common", "uncommon", "rare", "very_rare" -->
	<mineral name="hematite" frequency="common">
		<locale-list>
			<!-- locale topographical regions the mineral is located. -->
			<!-- Valid values: "volcanic", "sedimentary", "crater" -->
			<locale name="volcanic" />
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Magnetite is an iron ore with volcanic and metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Magnetite -->
	<mineral name="magnetite" frequency="rare">
		<locale-list>
			<locale name="volcanic" />
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Magnesite is a magnesium carbonate with metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Magnesite -->
	<mineral name="magnesite" frequency="rare">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Olivine is a magnesium iron silicate found in meteorites. -->
 	<!-- http://en.wikipedia.org/wiki/Olivine -->
	<mineral name="olivine" frequency="uncommon">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Goethite is an iron ore that has metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Goethite -->
	<mineral name="goethite" frequency="common">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Kamacite is an iron-nickel mineral found in meteorites. -->
	<!-- http://en.wikipedia.org/wiki/Kamacite -->
	<mineral name="kamacite" frequency="common">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Taenite is an iron-nickel mineral found in meteorites. -->
	<!-- http://en.wikipedia.org/wiki/Taenite -->
	<mineral name="taenite" frequency="common">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
	<!-- Chalcopyrite is a copper sulfide mineral. -->
	<!-- http://en.wikipedia.org/wiki/Chalcopyrite -->
	<mineral name="chalcopyrite" frequency="uncommon">
		<locale-list>
			<locale name="sedimentary" />
			<locale name="volcanic" />
		</locale-list>
	</mineral>
	
	<!-- Malachite is a copper carbonate mineral. -->
	<!-- http://en.wikipedia.org/wiki/Malachite -->
	<mineral name="malachite" frequency="uncommon">
		<locale-list>
			<locale name="sedimentary" />
			<locale name="volcanic" />
		</locale-list>
	</mineral>
	
	<!-- Sylvite is a salt concentration of potasium chloride. -->
	<!-- http://en.wikipedia.org/wiki/Sylvite -->
	<mineral name="sylvite" frequency="common">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
</mineral-concentrations>
