=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/parts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/parts"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:pa="http://mars-sim.sourceforge.net/parts">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="part-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pa:part" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="part">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pa:maintenance-entity-list" minOccurs="0"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="mass" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="maintenance-entity-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pa:entity" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="mass" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="entity">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="probability" type="xs:integer"></xs:attribute>
    		<xs:attribute name="max-number" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/parts.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- List of all parts in the simulation.  -->
<!-- Parts are used for maintenance, repair and manufacturing. -->
<part-list
	xmlns="http://mars-sim.sourceforge.net/parts"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mars-sim.sourceforge.net/parts schema/parts.xsd">

	<!-- Plastic and adhesive patch for airleaks. -->
	<!-- mass - The mass of the part in kilograms. -->
	<part name="airleak patch" mass=".2">
	
		<!-- List of entities that may required this part for maintenance. (optional) -->
		<maintenance-entity-list>
		
			<!-- probability - The percentage probability that at least one of this part -->
			<!--   will be needed for a given maintenance. -->
			<!-- max-number - The maximum number of this part that could be needed for a -->
			<!--   given maintenance. -->
			<entity name="life support" probability="10" max-number="4" />
			<entity name="rover" probability="10" max-number="2" />
			<entity name="eva suit" probability="10" max-number="1" />
			<entity name="farming" probability="10" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="co2 extinguisher" mass="20.0" />
	
	<!-- Rover wheels are made of steel and steel wire. -->
	<part name="rover wheel" mass="50.0">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="6" />
		</maintenance-entity-list>
	</part>
	
	<part name="gasket" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="30" max-number="4" />
			<entity name="farming" probability="60" max-number="6" />
			<entity name="living accomodations" probability="30" max-number="4" />
			<entity name="manufacture" probability="60" max-number="6" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="15" max-number="2" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="valve" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="20" max-number="2" />
			<entity name="farming" probability="30" max-number="3" />
			<entity name="living accomodations" probability="15" max-number="2" />
			<entity name="manufacture" probability="30" max-number="3" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="10" max-number="1" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="epoxy resin bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="50" max-number="6" />
			<entity name="farming" probability="80" max-number="12" />
			<entity name="living accomodations" probability="40" max-number="4" />
			<entity name="manufacture" probability="80" max-number="6" />
			<entity name="eva suit" probability="20" max-number="1" />
			<entity name="settlement" probability="20" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<part name="spark plug" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="30" max-number="2" />
		</maintenance-entity-list>
	</part>
	
	<part name="coolant bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="30" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="electrical wire" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="30" max-number="6" />
			<entity name="power generation" probability="20" max-number="4" />
			<entity name="manufacture" probability="20" max-number="4" />
			<entity name="settlement" probability="10" max-number="8" />
		</maintenance-entity-list>
	</part>
	
	<part name="power cable" mass="2.0">
		<maintenance-entity-list>
			<entity name="power generation" probability="10" max-number="2" />
			<entity name="settlement" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<part name="wire connector" mass=".1">
		<maintenance-entity-list>
			<entity name="vehicle" probability="30" max-number="6" />
			<entity name="power generation" probability="20" max-number="4" />
			<entity name="manufacture" probability="20" max-number="4" />
			<entity name="settlement" probability="10" max-number="8" />
		</maintenance-entity-list>
	</part>
	
	<part name="plastic tubing" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="10" max-number="4" />
			<entity name="farming" probability="30" max-number="10" />
			<entity name="manufacture" probability="60" max-number="10" />
			<entity name="settlement" probability="10" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<part name="lubricant bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="10" max-number="4" />
			<entity name="manufacture" probability="10" max-number="2" />
		</maintenance-entity-list>
	</part>
	
	<part name="rover battery" mass="50.0">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="light utility vehicle" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="radio antenna" mass="2.0">
		<maintenance-entity-list>
			<entity name="vehicle" probability="10" max-number="1" />
			<entity name="communication" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="satellite dish" mass="10.0">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="timing belt" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="30" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="communications circuit board" mass=".5">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="navigation circuit board" mass=".5">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="suit heating unit" mass="2.0">
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="plastic pipe" mass="1.0">
		<maintenance-entity-list>
			<entity name="living accomodations" probability="10" max-number="2" />
			<entity name="farming" probability="20" max-number="4" />
			<entity name="manufacture" probability="20" max-number="2" />
			<entity name="rover" probability="5" max-number="1" />
			<entity name="settlement" probability="10" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<part name="steel pipe" mass="10.0">
		<maintenance-entity-list>
			<entity name="farming" probability="10" max-number="2" />
			<entity name="manufacture" probability="10" max-number="2" />
			<entity name="rover" probability="10" max-number="1" />
			<entity name="settlement" probability="10" max-number="2" />
		</maintenance-entity-list>
	</part>
	
	<part name="iron pipe" mass="10.0">
		<maintenance-entity-list>
			<entity name="farming" probability="10" max-number="2" />
			<entity name="manufacture" probability="10" max-number="2" />
			<entity name="rover" probability="10" max-number="1" />
			<entity name="settlement" probability="10" max-number="2" />
		</maintenance-entity-list>
	</part>
	
	<part name="copper pipe" mass="5.0">
		<maintenance-entity-list>
			<entity name="living accomodations" probability="10" max-number="1" />
			<entity name="farming" probability="20" max-number="2" />
			<entity name="manufacture" probability="10" max-number="2" />
			<entity name="settlement" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="iron ingot" mass="5.0" />
	
	<part name="steel ingot" mass="5.0" />
	
	<part name="aluminum ingot" mass="1.0" />
	
	<part name="steel canister" mass="10.0" />
	
	<part name="bottle" mass=".1" />
	
	<!-- 1m x 2m x 1mm sheet of steel -->
	<part name="steel sheet" mass="15.0" />
	
	<!-- 1m x 2m x 1mm sheet of iron -->
	<part name="iron sheet" mass="15.0" />
	
	<!-- 1m x 2m x 1mm sheet of aluminum -->
	<part name="aluminum sheet" mass="5.0" />
	
	<!-- 1kg spool of thick steel wire -->
	<part name="steel wire" mass="1.0" />
	
	<!-- 5kg spool of thick steel cable -->
	<part name="steel cable" mass="5.0" />
	
	<!-- 1kg spool of thin aluminum wire -->
	<part name="aluminum wire" mass="1.0" />
	
	<!-- 1kg spool of thin fiberglass -->
	<part name="fiberglass" mass="1.0" />
	
	<!-- 1m x 1m square of woven fiberglass cloth -->
	<part name="fiberglass cloth" mass=".1" />
	
	<!-- 1m x 1m square of thin plastic sheet -->
	<part name="plastic sheet" mass=".1" />
	
	<!-- 1m x 1m x 1cm square of glass  -->
	<part name="glass sheet" mass="26.0" />
	
	<part name="eva helmet" mass="2.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="helmet visor" mass="2.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<!-- Spandex inner EVA suit for counter pressure. -->
	<part name="counter pressure suit" mass="1.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<!-- Outer EVA suit with insulative liner. -->
	<part name="coveralls" mass="2.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="eva gloves" mass="1.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<!-- steel soled and tipped.  Fiberglass insulated. -->
