=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/part_packages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/part-packages"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:pp="http://mars-sim.sourceforge.net/part-packages">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="part-package-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pp:part-package" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="part-package">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pp:part" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="part">
    	<xs:complexType>
    		<xs:attribute name="type" type="xs:string"></xs:attribute>
    		<xs:attribute name="number" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/part_packages.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- List of all part packages in the simulation. -->
<!-- Part packages are used for settlement initial supplies -->
<!-- and resupplies. (see settlement.xml) -->
<part-package-list
	xmlns="http://mars-sim.sourceforge.net/part-packages"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mars-sim.sourceforge.net/part-packages schema/part_packages.xsd">

	<!-- Part package -->
	<!-- name: the unique name of the package. -->
	<part-package name="package 1" >
		
		<!-- Parts -->
		<!-- type: the type of part (see parts.xml) -->
		<!-- number: the number of parts. -->
		<part type="airleak patch" number="105" />
		<part type="co2 extinguisher" number="15" />
		<part type="rover wheel" number="4" />
		<part type="gasket" number="85" />
		<part type="timing belt" number="10" />
		<part type="valve" number="42" />
		<part type="epoxy resin bottle" number="144" />
		<part type="spark plug" number="10" />
		<part type="coolant bottle" number="9" />
		<part type="electrical wire" number="1000" />
		<part type="power cable" number="48" />
		<part type="wire connector" number="1000" />
		<part type="plastic tubing" number="44" />
		<part type="lubricant bottle" number="6" />
		<part type="rover battery" number="2" />
		<part type="radio antenna" number="7" />
		<part type="satellite dish" number="3" />
		<part type="communications circuit board" number="3" />
		<part type="navigation circuit board" number="1" />
		<part type="suit heating unit" number="6" />
		<part type="plastic pipe" number="27" />
		<part type="steel pipe" number="10" />
		<part type="copper pipe" number="10" />
		<part type="iron pipe" number="10" />
		<part type="eva helmet" number="10" />
		<part type="helmet visor" number="10" />
		<part type="counter pressure suit" number="10" />
		<part type="coveralls" number="10" />
		<part type="eva gloves" number="10" />
		<part type="eva boots" number="10" />
		<part type="eva pads" number="10" />
		<part type="eva backpack" number="10" />
		<part type="eva antenna" number="10" />
		<part type="eva battery" number="10" />
		<part type="eva radio" number="10" />
		<part type="fuel pump" number="10" />
		<part type="oxygen pump" number="10" />
		<part type="rover windshield" number="1" />
		<part type="rover window" number="1" />
		<part type="winch" number="1" />
		<part type="small electric motor" number="1" />
		<part type="large electric motor" number="1" />
		<part type="rover chassis panel" number="1" />
		<part type="rover generator" number="1" />
		<part type="rover control panel" number="1" />
		<part type="rover fuel tank" number="1" />
		<part type="rover oxygen tank" number="1" />
		<part type="rover water tank" number="1" />
		<part type="electric heating element" number="5" />
		<part type="pneumatic drill" number="1" />
		<part type="backhoe" number="1" />
		<part type="bulldozer blade" number="1" />
		<part type="soil compactor" number="1" />
		<part type="crane boom" number="1" />
		<part type="small wheel" number="4" />
		<part type="utility vehicle control panel" number="1" />
		<part type="solar panel" number="1" />
		
	</part-package>
	
	<part-package name="package 2" >
	
		<part type="airleak patch" number="289" />
		<part type="co2 extinguisher" number="43" />
		<part type="rover wheel" number="18" />
		<part type="gasket" number="215" />
		<part type="timing belt" number="20" />
		<part type="valve" number="143" />
		<part type="epoxy resin bottle" number="371" />
		<part type="spark plug" number="46" />
		<part type="coolant bottle" number="46" />
		<part type="electrical wire" number="2000" />
		<part type="power cable" number="69" />
		<part type="wire connector" number="2000" />
		<part type="plastic tubing" number="95" />
		<part type="lubricant bottle" number="29" />
		<part type="rover battery" number="7" />
		<part type="radio antenna" number="20" />
		<part type="satellite dish" number="11" />
		<part type="communications circuit board" number="10" />
		<part type="navigation circuit board" number="6" />
		<part type="suit heating unit" number="19" />
		<part type="plastic pipe" number="48" />
		<part type="steel pipe" number="20" />
		<part type="copper pipe" number="20" />
		<part type="iron pipe" number="20" />
		<part type="eva helmet" number="20" />
		<part type="helmet visor" number="20" />
		<part type="counter pressure suit" number="20" />
		<part type="coveralls" number="20" />
		<part type="eva gloves" number="20" />
		<part type="eva boots" number="20" />
		<part type="eva pads" number="20" />
		<part type="eva backpack" number="20" />
		<part type="eva antenna" number="20" />
		<part type="eva battery" number="20" />
		<part type="eva radio" number="20" />
		<part type="fuel pump" number="20" />
		<part type="oxygen pump" number="20" />
		<part type="rover windshield" number="2" />
		<part type="rover window" number="2" />
		<part type="winch" number="2" />
		<part type="small electric motor" number="2" />
		<part type="large electric motor" number="2" />
		<part type="rover chassis panel" number="2" />
		<part type="rover generator" number="2" />
		<part type="rover control panel" number="2" />
		<part type="rover fuel tank" number="2" />
		<part type="rover oxygen tank" number="2" />
		<part type="rover water tank" number="2" />
		<part type="electric heating element" number="10" />
		<part type="pneumatic drill" number="1" />
		<part type="backhoe" number="1" />
		<part type="bulldozer blade" number="1" />
		<part type="soil compactor" number="1" />
		<part type="crane boom" number="1" />
		<part type="small wheel" number="4" />
		<part type="utility vehicle control panel" number="1" />
		<part type="solar panel" number="2" />
	
	</part-package>
	
	<part-package name="package 3">
	
		<part type="airleak patch" number="314" />
		<part type="co2 extinguisher" number="43" />
		<part type="rover wheel" number="19" />
		<part type="gasket" number="293" />
		<part type="timing belt" number="30" />
		<part type="valve" number="143" />
		<part type="epoxy resin bottle" number="485" />
		<part type="spark plug" number="55" />
		<part type="coolant bottle" number="50" />
		<part type="electrical wire" number="2500" />
		<part type="power cable" number="98" />
		<part type="wire connector" number="2500" />
		<part type="plastic tubing" number="135" />
		<part type="lubricant bottle" number="32" />
		<part type="rover battery" number="8" />
		<part type="radio antenna" number="28" />
		<part type="satellite dish" number="14" />
		<part type="communications circuit board" number="14" />
		<part type="navigation circuit board" number="7" />
		<part type="suit heating unit" number="19" />
		<part type="plastic pipe" number="71" />
		<part type="steel pipe" number="30" />
		<part type="copper pipe" number="30" />
		<part type="iron pipe" number="30" />
		<part type="eva helmet" number="30" />
		<part type="helmet visor" number="30" />
		<part type="counter pressure suit" number="30" />
		<part type="coveralls" number="30" />
		<part type="eva gloves" number="30" />
		<part type="eva boots" number="30" />
		<part type="eva pads" number="30" />
		<part type="eva backpack" number="30" />
		<part type="eva antenna" number="30" />
		<part type="eva battery" number="30" />
		<part type="eva radio" number="30" />
		<part type="fuel pump" number="30" />
		<part type="oxygen pump" number="30" />
		<part type="rover windshield" number="2" />
		<part type="rover window" number="3" />
		<part type="winch" number="3" />
		<part type="small electric motor" number="3" />
		<part type="large electric motor" number="3" />
		<part type="rover chassis panel" number="3" />
		<part type="rover generator" number="3" />
		<part type="rover control panel" number="3" />
		<part type="rover fuel tank" number="3" />
		<part type="rover oxygen tank" number="3" />
		<part type="rover water tank" number="3" />
		<part type="electric heating element" number="15" />
		<part type="pneumatic drill" number="2" />
		<part type="backhoe" number="2" />
		<part type="bulldozer blade" number="2" />
		<part type="soil compactor" number="2" />
		<part type="crane boom" number="2" />
		<part type="small wheel" number="8" />
		<part type="utility vehicle control panel" number="2" />
		<part type="solar panel" number="3" />
		
	</part-package>
	
	<part-package name="package 4">
	
		<part type="airleak patch" number="401" />
		<part type="co2 extinguisher" number="64" />
		<part type="rover wheel" number="19" />
		<part type="gasket" number="329" />
		<part type="timing belt" number="40" />
		<part type="valve" number="156" />
		<part type="epoxy resin bottle" number="528" />
		<part type="spark plug" number="55" />
		<part type="coolant bottle" number="50" />
		<part type="electrical wire" number="5000" />
		<part type="power cable" number="143" />
		<part type="wire connector" number="5000" />
		<part type="plastic tubing" number="169" />
		<part type="lubricant bottle" number="32" />
		<part type="rover battery" number="8" />
		<part type="radio antenna" number="28" />
		<part type="satellite dish" number="14" />
		<part type="communications circuit board" number="14" />
		<part type="navigation circuit board" number="7" />
		<part type="suit heating unit" number="23" />
		<part type="plastic pipe" number="94" />
		<part type="steel pipe" number="40" />
		<part type="copper pipe" number="40" />
		<part type="iron pipe" number="40" />
		<part type="eva helmet" number="40" />
		<part type="helmet visor" number="40" />
		<part type="counter pressure suit" number="40" />
		<part type="coveralls" number="40" />
		<part type="eva gloves" number="40" />
		<part type="eva boots" number="40" />
		<part type="eva pads" number="40" />
		<part type="eva backpack" number="40" />
		<part type="eva antenna" number="40" />
		<part type="eva battery" number="40" />
		<part type="eva radio" number="40" />
		<part type="fuel pump" number="40" />
