=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/people.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/people"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:pe="http://mars-sim.sourceforge.net/people">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="people-configuration">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pe:oxygen-consumption-rate"></xs:element>
    			<xs:element ref="pe:water-consumption-rate"></xs:element>
    			<xs:element ref="pe:food-consumption-rate"></xs:element>
    			<xs:element ref="pe:oxygen-deprivation-time"></xs:element>
    			<xs:element ref="pe:water-deprivation-time"></xs:element>
    			<xs:element ref="pe:food-deprivation-time"></xs:element>
    			<xs:element ref="pe:starvation-start-time"></xs:element>
    			<xs:element ref="pe:min-air-pressure"></xs:element>
    			<xs:element ref="pe:decompression-time"></xs:element>
    			<xs:element ref="pe:min-temperature"></xs:element>
    			<xs:element ref="pe:max-temperature"></xs:element>
    			<xs:element ref="pe:freezing-time"></xs:element>
    			<xs:element ref="pe:stress-breakdown-chance"></xs:element>
    			<xs:element ref="pe:gender-male-percentage"></xs:element>
    			<xs:element ref="pe:personality-types"></xs:element>
    			<xs:element ref="pe:person-name-list"></xs:element>
    			<xs:element ref="pe:person-list"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="oxygen-consumption-rate">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="water-consumption-rate">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="food-consumption-rate">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="oxygen-deprivation-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="water-deprivation-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="food-deprivation-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="starvation-start-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="min-air-pressure">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="decompression-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="min-temperature">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="max-temperature">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="freezing-time">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="stress-breakdown-chance">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="gender-male-percentage">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="personality-types">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pe:mbti" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="mbti">
    	<xs:complexType>
    		<xs:attribute name="type" type="xs:string"></xs:attribute>
    		<xs:attribute name="percentage" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="person-name-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pe:person-name" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="person-name">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:string"></xs:attribute>
    		<xs:attribute name="gender" type="conf:gender"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="person-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pe:person" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="person">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pe:natural-attribute-list" minOccurs="0"></xs:element>
    			<xs:element ref="pe:skill-list" minOccurs="0"></xs:element>
    			<xs:element ref="pe:relationship-list" minOccurs="0"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="gender" type="conf:gender"></xs:attribute>
    		<xs:attribute name="personality-type" type="xs:string"></xs:attribute>
    		<xs:attribute name="settlement" type="xs:string"></xs:attribute>
    		<xs:attribute name="job" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="natural-attribute-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pe:natural-attribute" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="natural-attribute">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="value" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="skill-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pe:skill" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="skill">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="level" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="relationship-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="pe:relationship" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="relationship">
    	<xs:complexType>
    		<xs:attribute name="person-name" type="xs:string"></xs:attribute>
    		<xs:attribute name="opinion" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/people.xml
<?xml version="1.0" encoding="UTF-8"?>

<people-configuration
	xmlns="http://mars-sim.sourceforge.net/people"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mars-sim.sourceforge.net/people schema/people.xsd">

	<!-- The average amount of oxygen (kg) breathed by a person each Martian Sol -->
	<!-- Default: 1.0 -->
	<oxygen-consumption-rate value="1.0" />

	<!-- The average amount of water (kg) drank by a person each Martian Sol -->
	<!-- Default: 4.0 -->
	<water-consumption-rate value="4.0" />

	<!-- The average amount of food (kg) eaten by a person each Martian Sol -->
	<!-- Default: 1.5 -->
	<food-consumption-rate value="1.5" />

	<!-- Number of millisols a person can survive without oxygen -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<!-- Default: 3.38 -->
	<oxygen-deprivation-time value="3.38" />

	<!-- Number of sols a person can survive without water -->
	<!-- Default: 6.0 -->
	<water-deprivation-time value="6.0" />

	<!-- Number of sols a person can survive without food -->
	<!-- Default: 21.0 -->
	<food-deprivation-time value="21.0" />
	
	<!-- Number of sols a person can go without food before starvation sets in -->
	<!-- Default: 3.0 -->
	<starvation-start-time value="3.0" />

	<!-- Minimum air pressure (atm) a person can withstand without harm -->
	<!-- Default: .25 -->
	<min-air-pressure value=".25" />

	<!-- Number of millisols a person can survive in decompression -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<!-- Default: 1.0 -->
	<decompression-time value="1.0" />

	<!-- Minimum temperature (degrees celsius) a person can withstand without harm -->
	<!-- Default: 0 degrees celsius -->
	<min-temperature value="0.0" />

	<!-- Maximum temperature (degrees celsius) a person can withstand without harm -->
	<!-- Default: 48 degrees celsius -->
	<max-temperature value="48.0" />
	
	<!-- Number of millisols a person can survive below minimum temperature -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<!-- Default: 160.0 -->
	<freezing-time value="160.0" />
	
	<!-- Base percent chance per millisol that a person at maximum stress will have an anxiety attack. -->
	<!-- See medical complaint: "Anxiety Attack" in medical.xml. -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<!-- Default: .1 -->
	<stress-breakdown-chance value=".1" />

	<!-- The average percentage of males to total population in the simulation. -->
	<!-- Default 50 (equal numbers of males and females) -->
	<gender-male-percentage value="50.0" />
	
	<!-- The average percentages of the 16 MBTI (Myers-Briggs Type Indicator) personality types among settlers. -->
	<!-- Myers-Briggs Type Indicator: http://www.wikipedia.org/wiki/MBTI -->
	<!-- Note: The total percentage for all personality types must equal 100%. -->
	<!-- TODO: Find percentage statistics appropriate for Martian settlers, perhaps statistics studies of scientists, -->
	<!-- engineers or computer programmers. -->
	<personality-types>
		<mbti type="ISTP" percentage="3.0" />
		<mbti type="ISTJ" percentage="19.0" />
		<mbti type="ISFP" percentage="2.0" />
		<mbti type="ISFJ" percentage="8.0" />
		<mbti type="INTP" percentage="6.0" />
		<mbti type="INTJ" percentage="7.0" />
		<mbti type="INFP" percentage="6.0" />
		<mbti type="INFJ" percentage="5.0" />
		<mbti type="ESTP" percentage="2.0" />
		<mbti type="ESTJ" percentage="13.0" />
		<mbti type="ESFP" percentage="2.0" />
		<mbti type="ESFJ" percentage="8.0" />
		<mbti type="ENTP" percentage="4.0" />
		<mbti type="ENTJ" percentage="3.0" />
		<mbti type="ENFP" percentage="7.0" />
		<mbti type="ENFJ" percentage="5.0" />		
	</personality-types>

	<!-- List of person names -->
	<person-name-list>		

		<person-name value="Scott Davis" gender="male" />
		<person-name value="Mike Jones" gender="male" />
		<person-name value="Steve Marley" gender="male" />
		<person-name value="Oscar Carrol" gender="male" />
		<person-name value="Connie Carrol" gender="female" />
		<person-name value="Isabella Carrol" gender="female" />
		<person-name value="Michael Zummo" gender="male" />
		<person-name value="Tom Zanoni" gender="male" />
		<person-name value="Joseph Wagner" gender="male" />
		<person-name value="Troy Lane" gender="male" />
		<person-name value="Anson Nichols" gender="male" />
		<person-name value="Libby Parker" gender="female" />
		<person-name value="Charles Kwiatkowski" gender="male" />
		<person-name value="Kerrie Vaughan" gender="female" />
		<person-name value="Shawn Malmarowski" gender="male" />
		<person-name value="Peter Kokh" gender="male" />
		<person-name value="Matthew Giovanelli" gender="male" />
		<person-name value="Karen Neder" gender="female" />
		<person-name value="Doug Armstrong" gender="male" />
		<person-name value="Bill Hensley" gender="male" />
		<person-name value="Heidi Hensley" gender="female" />
		<person-name value="Kendra Hensley" gender="female" />
		<person-name value="Greg Whelan" gender="male" />
		<person-name value="Jennifer Hare" gender="female" />
		<person-name value="David Kern" gender="male" />
		<person-name value="Gregory Brown" gender="male" />
		<person-name value="Ray Kerchoff" gender="male" />
		<person-name value="Victor Plantico" gender="male" />
		<person-name value="Mark Chiappetta" gender="male" />
		<person-name value="Michael Sobecke" gender="male" />
		<person-name value="Dan Folker" gender="male" />
		<person-name value="Donna Hanson" gender="female" />
		<person-name value="Jeri Axberg" gender="female" />
		<person-name value="Jill Babbitz" gender="female" />
		<person-name value="Enrique Deorbeta" gender="male" />
		<person-name value="Tracy Hauck" gender="female" />
		<person-name value="Bill Krushas" gender="male" />
		<person-name value="Alexandria Luciano" gender="female" />
		<person-name value="Douglas McMartin" gender="male" />
		<person-name value="Marina Plavnick" gender="female" />
		<person-name value="Salvatorie Schifano" gender="male" />
		<person-name value="Kerrie Stolpman" gender="female" />
		<person-name value="Scott Walsh" gender="male" />
		<person-name value="Rory Wright" gender="male" />
		<person-name value="Jay Bondowzewski" gender="male" />
		<person-name value="Frank Alioto" gender="male" />
		<person-name value="Mary Carlson" gender="female" />
		<person-name value="Adrian Chan" gender="male" />
		<person-name value="Carla Deprey" gender="female" />
		<person-name value="John Derkson" gender="male" />
		<person-name value="Ramiro Ferrucci" gender="male" />
		<person-name value="Daniel Frankowiak" gender="male" />
		<person-name value="Anna Harmon" gender="female" />
		<person-name value="Tim Kaplan" gender="male" />
		<person-name value="David Ksiciski" gender="male" />
		<person-name value="Shizhe Li" gender="male" />
		<person-name value="Kent Primrose" gender="male" />
		<person-name value="Steven Hirth" gender="male" />
		<person-name value="Charlie Elston" gender="male" />
		<person-name value="David Blundon" gender="male" />
		<person-name value="Denise Gregory" gender="female" />
		<person-name value="Edgar Crisostomo" gender="male" />
		<person-name value="Evelyn Garcia" gender="female" />
		<person-name value="Nathan Ellis" gender="male" />
		<person-name value="Brian Cody" gender="male" />
		<person-name value="Mary Hirn" gender="female" />
		<person-name value="Al Haldemann" gender="male" />
		<person-name value="Loretta Thomas" gender="female" />
		<person-name value="Beth Miller" gender="female" />
		<person-name value="Edward Bliese" gender="male" />
		<person-name value="Bruce Franke" gender="male" />
		<person-name value="Robert Laloggia" gender="male" />
		<person-name value="Chris Sundberg" gender="male" />
		<person-name value="Frank Di Pierro" gender="male" />
		<person-name value="Ron Johnson" gender="male" />
		<person-name value="Dushan Novakovich" gender="male" />
		<person-name value="Clair Steele" gender="female" />
		<person-name value="Joe Cifaldi" gender="male" />
		<person-name value="Jennifer Lorbeck" gender="female" />
		<person-name value="Eddie Hintz" gender="male" />
		<person-name value="Reginia Thomas" gender="female" />
		<person-name value="Elmer Brow" gender="male" />
		<person-name value="Sandra Blunt" gender="female" />
		<person-name value="Amy Lentz" gender="female" />
		<person-name value="Anthony Holmgren" gender="male" />
		<person-name value="Frank Krawczyk" gender="male" />
		<person-name value="James Silkworth" gender="male" />
		<person-name value="Joseph Alioto" gender="male" />
		<person-name value="Alessandra Kucharski" gender="female" />
		<person-name value="Aaron Wolfe" gender="male" />
		<person-name value="Evelyn Clinton" gender="female" />
		<person-name value="William Hickson" gender="male" />
		<person-name value="Jeanne Marak" gender="female" />
		<person-name value="Sally Krueger" gender="female" />
		<person-name value="Ernest Coletti" gender="male" />
		<person-name value="Fred Luehrs" gender="male" />
		<person-name value="Kelly Youngs" gender="female" />
		<person-name value="Sheldon Burchman" gender="male" />
		<person-name value="Randy Jorden" gender="male" />
		<person-name value="Dale Morrell" gender="male" />
		<person-name value="Dean Gluege" gender="male" />
		<person-name value="Ralph Radske" gender="male" />
		<person-name value="Michael Lucus" gender="male" />
		<person-name value="Charles Emery" gender="male" />
		<person-name value="Kelly Huckaby" gender="female" />
		<person-name value="Craig Jeffords" gender="male" />
		<person-name value="Tony Hudy" gender="male" />
		<person-name value="Dorothy Piatek" gender="female" />
		<person-name value="Allison Nowakowski" gender="female" />
		<person-name value="Rachel Heron" gender="female" />
		<person-name value="Jean Backes" gender="female" />
		<person-name value="Colleen Lane" gender="female" />
		<person-name value="Paul Bockay" gender="male" />
		<person-name value="Mike Halder" gender="male" />
		<person-name value="Scott Kaszuba" gender="male" />
