=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/resources.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/resources"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:res="http://mars-sim.sourceforge.net/resources">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="resource-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="res:resource" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="resource">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="phase">
    			<xs:simpleType>
   					<xs:restriction base="xs:string">
   						<xs:enumeration value="solid"></xs:enumeration>
   						<xs:enumeration value="liquid"></xs:enumeration>
   						<xs:enumeration value="gas"></xs:enumeration>
   					</xs:restriction>
   				</xs:simpleType>
    		</xs:attribute>
    		<xs:attribute name="life-support" type="xs:boolean"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/resources.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- List of all amount resources in the simulation. -->
<resource-list
	xmlns="http://mars-sim.sourceforge.net/resources"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mars-sim.sourceforge.net/resources schema/resources.xsd">

	<!-- Potable water -->
	<!-- name - the name of the resource. -->
	<!-- phase - the normal phase of the resource as used. -->
	<!--         Possible values: "solid", "liquid" or "gas" -->
	<!-- life-support - Is the resources used for life support? -->
	<resource name="water" phase="liquid" life-support="true" />
	
	<resource name="oxygen" phase="gas" life-support="true" />
	<resource name="hydrogen" phase="gas" life-support="false" />
	<resource name="methane" phase="gas" life-support="false" />
	<resource name="carbon dioxide" phase="gas" life-support="false" />
	<resource name="carbon monoxide" phase="gas" life-support="false" />
	
	<!-- Represents general freeze dried food. -->
	<resource name="food" phase="solid" life-support="true" />
	
	<!-- Rock samples collected from explored sites. -->
	<resource name="rock samples" phase="solid" life-support="false" />
	
	<!-- Sewage water used as crop fertilizer. -->
	<resource name="waste water" phase="liquid" life-support="false" />
	
	<!-- Ice-rich permafrost soil -->
	<resource name="ice" phase="solid" life-support="false" />
	
	<!-- Martian soil -->
	<resource name="regolith" phase="solid" life-support="false" />
	
	<resource name="iron oxide" phase="solid" life-support="false" />
	
	<!-- Carbon powder -->
	<resource name="carbon" phase="solid" life-support="false" />
	
	<!-- Martian soil with iron oxide removed. Used for making glass. -->
	<resource name="sand" phase="solid" life-support="false" />
	
	<resource name="iron powder" phase="solid" life-support="false" />
	<resource name="aluminum oxide" phase="solid" life-support="false" />
	<resource name="ethylene" phase="gas" life-support="false" />
	
	<!-- Polyethylene pellets or flakes. -->
	<resource name="polyethylene" phase="solid" life-support="false" />
	
	<resource name="gypsum" phase="solid" life-support="false" />
	<resource name="calcium carbonate" phase="solid" life-support="false" />
	<resource name="lime" phase="solid" life-support="false" />
	<resource name="styrene" phase="solid" life-support="false" />
	<resource name="polyester resin" phase="liquid" life-support="false" />
	
	<!-- Mineral concentrations. -->
	<resource name="hematite" phase="solid" life-support="false" />
	<resource name="magnetite" phase="solid" life-support="false" />
	<resource name="magnesite" phase="solid" life-support="false" />
	<resource name="olivine" phase="solid" life-support="false" />
	<resource name="goethite" phase="solid" life-support="false" />
	<resource name="kamacite" phase="solid" life-support="false" />
	<resource name="taenite" phase="solid" life-support="false" />
	<resource name="chalcopyrite" phase="solid" life-support="false" />
	<resource name="malachite" phase="solid" life-support="false" />
	<resource name="sylvite" phase="solid" life-support="false" />

	<resource name="nickel" phase="solid" life-support="false" />
	<resource name="sulfur" phase="solid" life-support="false" />
	<resource name="magnesium" phase="solid" life-support="false" />
	<resource name="silicon" phase="solid" life-support="false" />
	<resource name="copper" phase="solid" life-support="false" />
	
	<!-- Potassium hydroxide -->
	<resource name="potash lye" phase="solid" life-support="false" />

	<resource name="cement" phase="solid" life-support="false" />
	<resource name="concrete" phase="solid" life-support="false" />
	<resource name="mortar" phase="solid" life-support="false" />

</resource-list>
