=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/resupplies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/resupplies"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:rsp="http://mars-sim.sourceforge.net/resupplies">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="resupply-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="rsp:resupply" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="resupply">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="rsp:building" minOccurs="0" maxOccurs="unbounded"></xs:element>
    			<xs:element ref="rsp:vehicle" minOccurs="0" maxOccurs="unbounded"></xs:element>
    			<xs:element ref="rsp:equipment" minOccurs="0" maxOccurs="unbounded"></xs:element>
    			<xs:element ref="rsp:person" minOccurs="0" maxOccurs="unbounded"></xs:element>
    			<xs:element ref="rsp:resource" minOccurs="0" maxOccurs="unbounded"></xs:element>
    			<xs:element ref="rsp:part" minOccurs="0" maxOccurs="unbounded"></xs:element>
    			<xs:element ref="rsp:part-package" minOccurs="0" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="building">
    	<xs:complexType>
    		<xs:attribute name="type" type="xs:string"></xs:attribute>
    		<xs:attributeGroup ref="conf:positionAttributes"></xs:attributeGroup>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="vehicle">
    	<xs:complexType>
    		<xs:attribute name="type" type="xs:string"></xs:attribute>
    		<xs:attribute name="number" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="equipment">
    	<xs:complexType>
    		<xs:attribute name="type" type="xs:string"></xs:attribute>
    		<xs:attribute name="number" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="person">
    	<xs:complexType>
    		<xs:attribute name="number" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="resource">
    	<xs:complexType>
    		<xs:attribute name="type" type="xs:string"></xs:attribute>
    		<xs:attribute name="amount" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="part">
    	<xs:complexType>
    		<xs:attribute name="type" type="xs:string"></xs:attribute>
    		<xs:attribute name="number" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="part-package">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    		<xs:attribute name="number" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/resupplies.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Settlement resupply missions from Earth. -->
<resupply-list
	xmlns="http://mars-sim.sourceforge.net/resupplies"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mars-sim.sourceforge.net/resupplies schema/resupplies.xsd">

	<!-- Resupply mission from Earth. -->
	<!-- name: the unique name of the resupply mission. -->
	<resupply name="Mars Direct Base resupply 1">
	
		<!-- A new building for the settlement. -->
		<!-- type: the type of building (see buildings.xml) -->
		<!-- x-location the preferred East/West placement position of the building in meters from the settlement center. 
		     (positive:West, negative:East) -->
		<!-- y-location the preferred North/South placement position of the building in meters from the settlement center. 
		     (positive:North, negative:South) -->
		<!-- The facing of the building in degrees clockwise from North. -->
		<building type="Lander Hab" x-location="0.0" y-location="9.0" facing="0.0" />
		
		<building type="Inflatable Greenhouse" x-location="-9.0" y-location="9.0" facing="270.0" />
		<building type="MD1 Nuclear Reactor" x-location="-52.0" y-location="-68.0" facing="0.0" />
		<building type="Starting ERV Base" x-location="40.0" y-location="45.0" facing="135.0" />
		
		<!-- New equipment -->
		<!-- type: the type of equipment. -->
		<!-- number: the number of this type of equipment. -->
		<equipment type="EVA Suit" number="8" />
		<equipment type="Gas Canister" number="10" />
		<equipment type="Bag" number="10" />
		<equipment type="Large Bag" number="10" />
		<equipment type="Barrel" number="10" />
		
		<!-- New immigrants from Earth. -->
		<!-- number: the number of immigrants. -->
		<person number="4" />
		
		<!-- Resource provided in this resupply. -->
		<!-- type: the type of resource (see resources.txt) -->
		<!-- amount: the amount of the resource (kg) -->
		<resource type="hydrogen" amount="1000.0" />
		<resource type="food" amount="500.0" />
			
		<!-- Part packages (see part_packages.xml) -->
		<!-- name: the part package name. -->
		<!-- number: the number of packages. -->
		<part-package name="package 2" number="1" />
			
	</resupply>
		
	<resupply name="Mars Direct Base resupply 2">
		<building type="Lander Hab" x-location="0.0" y-location="18.0" facing="0.0" />
		<building type="Inflatable Greenhouse" x-location="-9.0" y-location="18.0" facing="270.0" />
		<building type="MD1 Nuclear Reactor" x-location="-62.0" y-location="-68.0" facing="0.0" />
		<building type="Starting ERV Base" x-location="70.0" y-location="15.0" facing="90.0" />
		<vehicle type="Explorer Rover" number="1" />
		<vehicle type="Transport Rover" number="1" />
		<vehicle type="Light Utility Vehicle" number="1" />
		<equipment type="EVA Suit" number="8" />
		<equipment type="Gas Canister" number="10" />
		<equipment type="Barrel" number="10" />
		<equipment type="Bag" number="20" />
		<equipment type="Large Bag" number="10" />
		<equipment type="Specimen Box" number="20" />
		<person number="4" />
		<resource type="hydrogen" amount="1000.0" />
		<resource type="food" amount="500.0" />
		<part-package name="package 3" number="1" />
	</resupply>
		
	<resupply name="Mars Direct Base resupply 3">
		<building type="Atmospheric Processor" x-location="0.0" y-location="-20.0" facing="90.0" />
		<building type="Residential Quarters" x-location="-18.0" y-location="26.0" facing="270.0" />
		<building type="Lounge" x-location="-9.0" y-location="26.0" facing="270.0" />
		<building type="Infirmary" x-location="-27.0" y-location="26.0" facing="270.0" />
		<building type="Command and Control" x-location="0.0" y-location="26.0" facing="270.0" />
		<building type="Large Greenhouse" x-location="-36.0" y-location="13.5" facing="0.0" />
		<building type="Laboratory" x-location="-36.0" y-location="26.0" facing="270.0" />
		<building type="Garage" x-location="-45.0" y-location="37.5" facing="0.0" />
		<building type="Workshop" x-location="-45.0" y-location="26.0" facing="270.0" />
		<building type="MD4 Nuclear Reactor" x-location="25.0" y-location="-57.5" facing="0.0" />
		<building type="MD4 Nuclear Reactor" x-location="40.0" y-location="-57.5" facing="0.0" />
		<building type="Astronomy Observatory" x-location="-62.5" y-location="-17.5" facing="90.0" />
		<vehicle type="Explorer Rover" number="2" />
		<vehicle type="Transport Rover" number="2" />
		<vehicle type="Light Utility Vehicle" number="1" />
		<equipment type="EVA Suit" number="24" />
		<equipment type="Gas Canister" number="10" />
		<equipment type="Barrel" number="10" />
		<equipment type="Bag" number="40" />
		<equipment type="Large Bag" number="10" />
		<equipment type="Specimen Box" number="40" />
		<person number="12" />
		<resource type="hydrogen" amount="1000.0" />
		<resource type="food" amount="500.0" />
		<part-package name="package 4" number="1" />
	</resupply>
	
</resupply-list>
