=== mars-sim/releases/mars-sim-config/src/main/resources/config/schema/vehicles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://mars-sim.sourceforge.net/vehicles"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://mars-sim.sourceforge.net/configuration"
	xmlns:v="http://mars-sim.sourceforge.net/vehicles">

	<xs:import schemaLocation="configuration.xsd" namespace="http://mars-sim.sourceforge.net/configuration"></xs:import>
    
    <xs:element name="vehicle-configuration">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="v:vehicle" maxOccurs="unbounded"></xs:element>
    			<xs:element ref="v:rover-name-list"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="vehicle">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="v:description" maxOccurs="1" minOccurs="0"></xs:element>
    			<xs:element ref="v:fuel-efficiency"></xs:element>
    			<xs:element ref="v:base-speed"></xs:element>
    			<xs:element ref="v:empty-mass"></xs:element>
    			<xs:element ref="v:crew-size" minOccurs="0"></xs:element>
    			<xs:element ref="v:cargo" minOccurs="0"></xs:element>
    			<xs:element ref="v:part-attachment" minOccurs="0"></xs:element>
    			<xs:element ref="v:sickbay" minOccurs="0"></xs:element>
    			<xs:element ref="v:lab" minOccurs="0"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="type" type="xs:string"></xs:attribute>
    		<xs:attributeGroup ref="conf:rectangleAttributes"></xs:attributeGroup>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="description" type="xs:string"></xs:element>

    <xs:element name="fuel-efficiency">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="base-speed">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="empty-mass">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="crew-size">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="cargo">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="v:capacity" minOccurs="0" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="total-capacity" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="capacity">
    	<xs:complexType>
    		<xs:attribute name="resource" type="xs:string"></xs:attribute>
    		<xs:attribute name="value" type="xs:double"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="part-attachment">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="v:part" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="number-slots" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="part">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="sickbay">
    	<xs:complexType>
    		<xs:attribute name="tech-level" type="xs:integer"></xs:attribute>
    		<xs:attribute name="beds" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="lab">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="v:tech-speciality" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    		<xs:attribute name="tech-level" type="xs:integer"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="tech-speciality">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="rover-name-list">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="v:rover-name" maxOccurs="unbounded"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
    
    <xs:element name="rover-name">
    	<xs:complexType>
    		<xs:attribute name="value" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>
    
</xs:schema>

=== mars-sim/releases/mars-sim-config/src/main/resources/config/vehicles.xml
<?xml version="1.0" encoding="UTF-8"?>

<vehicle-configuration
	xmlns="http://mars-sim.sourceforge.net/vehicles"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mars-sim.sourceforge.net/vehicles schema/vehicles.xsd">

	<vehicle type="Explorer Rover" width="3.5" length="8.0">
		<description>A rover for collecting rock samples from remote sites and ice prospecting.</description>

		<!-- The fuel efficiency of the rover (km/kg) (required) -->
		<!-- Default: 2.0 -->
		<fuel-efficiency value="2.0" />

		<!-- Base speed of rover (km/hr) (required) -->
		<!-- Default: 30.0 -->
		<base-speed value="30.0" />

		<!-- Empty mass of rover (kg) (required) -->
		<!-- Default: 10000.0 -->
		<empty-mass value="10000.0" />

		<!-- The crew size of an rover -->
		<!-- Default: 4 -->
		<crew-size value="4" />

		<!-- Cargo capacity list -->
		<!-- total-capacity: total cargo capacity of rover. (kg) -->
		<!-- Default: 5500.0 -->
		<cargo total-capacity="5500.0">
 
			<!-- The methane cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 1600.0 -->
			<capacity resource="Methane" value="1600.0" />

			<!-- The oxygen cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 140.0 -->
			<capacity resource="Oxygen" value="140.0" />

			<!-- The water cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 560.0 -->
			<capacity resource="Water" value="560.0" />

			<!-- The food cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 210.0 -->
			<capacity resource="Food" value="210.0" />

			<!-- The rock samples cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 2000.0 -->
			<!-- <capacity resource="Rock Samples" value="2000.0" /> -->

			<!-- The ice cargo capacity of the rover (kg) -->
			<!-- See resources.txt -->
			<!-- Default: 2000.0 -->
			<!-- <capacity resource="Ice" value="2000.0" /> -->

		</cargo>

		<!-- Sickbay -->
		<!-- Medical tech level of sickbay (see tech_level.txt) - default: 1 -->
		<!-- Number of beds in sickbay - default: 1 -->
		<sickbay tech-level="1" beds="1" />

		<!-- Lab -->
		<!-- Science tech level of lab (see tech_level.txt) - default: 1 -->
		<lab tech-level="1">
			<!-- Science tech specialty -->
			<tech-specialty value="Areology" />
			<tech-specialty value="Biology" />
		</lab>

	</vehicle>

	<!-- Transport rover -->
	<vehicle type="Transport Rover" width="3.5" length="9.5">
		<description>A rover for transporting people from one settlement to another.</description>
		<fuel-efficiency value="2.0" />
		<base-speed value="30.0" />
		<empty-mass value="10000.0" />
		<crew-size value="8" />
		<cargo total-capacity="7000.0">
			<capacity resource="Methane" value="2000.0" />
			<capacity resource="Oxygen" value="350.0" />
			<capacity resource="Water" value="1400.0" />
			<capacity resource="Food" value="525.0" />            
		</cargo>
		<sickbay tech-level="3" beds="2" />
	</vehicle>
	
	<!-- Cargo rover -->
	<vehicle type="Cargo Rover" width="4.0" length="8.0">
		<description>A rover for transporting cargo from one settlement to another.</description>
		<fuel-efficiency value="2.0" />
		<base-speed value="30.0" />
		<empty-mass value="10000.0" />
		<crew-size value="2" />
		<cargo total-capacity="10000.0">
			<capacity resource="Methane" value="2000.0" />
			<capacity resource="Oxygen" value="350.0" />
			<capacity resource="Water" value="1400.0" />
			<capacity resource="Food" value="525.0" />            
		</cargo>
		<sickbay tech-level="1" beds="1" />
	</vehicle>
	
	<!-- Light Utility Vehicle -->
	<vehicle type="Light Utility Vehicle" width="1.7" length="2.55">
		<description>A small, unpressurized, one crew utility vehicle with attachable parts.</description>
		<fuel-efficiency value="0.0" />
		<base-speed value="0.0" />
		<empty-mass value="300.0" />
		<crew-size value="1" />
		<cargo total-capacity="400.0" />
		<part-attachment number-slots="2">
            <part name="bulldozer blade" />
			<part name="pneumatic drill" />
			<part name="backhoe" />
			<part name="soil compactor" />
			<part name="drilling rig" />
			<part name="crane boom" />
		</part-attachment>
	</vehicle>
	
	<!-- List of rover names -->
	<rover-name-list>		

		<rover-name value="Dune Drifter" />
		<rover-name value="Oasis" />
		<rover-name value="Sun Dancer" />
		<rover-name value="Desert Fox" />
		<rover-name value="Serenity" />
		<rover-name value="Gypsea" />
		<rover-name value="Martian Cloud" />	
		<rover-name value="Sand Spirit" />
		<rover-name value="Dust Sprite" />
		<rover-name value="Phobos Drifter" />
		<rover-name value="Osprey" />
		<rover-name value="Dune Runner" />
		<rover-name value="Wind Runner" />
		<rover-name value="Sand Dancer" />	
		<rover-name value="Nomad" />
		<rover-name value="Spice Trader" />
		<rover-name value="Solitude" />
		<rover-name value="Dust Storm" />
		<rover-name value="Martian Escape" />
		<rover-name value="Odyssey" />
		<rover-name value="Deimos Tide" />	
		<rover-name value="Red Mariner" />
		<rover-name value="Shooting Star" />
		<rover-name value="Dust Devil" />
		<rover-name value="Desert Star" />
		<rover-name value="Windstorm" />
		<rover-name value="Drift Wood" />
		<rover-name value="Desertfarer" />
		<rover-name value="Dream Chaser" />	
		<rover-name value="Bedouin" />	
		<rover-name value="Fremen Wanderer" />
		<rover-name value="Beagle IV" />	
		<rover-name value="Firefly" />
		<rover-name value="Desert Pearl" />
		<rover-name value="Princess of the Sands" />
		<rover-name value="Ridge Runner" />
		<rover-name value="Desert Rose" />
		<rover-name value="Crater Crab" />
		<rover-name value="Red Moon" />
		<rover-name value="Sand Crawler" />
		<rover-name value="Sojourner II" />
		<rover-name value="Spirit II" />
		<rover-name value="Opportunity II" />
		<rover-name value="Fire Star" />
		<rover-name value="Rahu" /> <!-- Hindi for "Mars" (not certain) -->
		<rover-name value="Vayu" /> <!-- Hindi for "wind" -->
		<rover-name value="Agni" /> <!-- Hindi for "fire" -->
		<rover-name value="Prithvi" /> <!-- Hindi for "earth" -->
		<rover-name value="Reth" /> <!-- Hindi for "sand" -->
		<rover-name value="Naag" /> <!-- Hindi for "snake" -->
		<rover-name value="Mangala" /> <!-- Mars in Jyotish astrology -->
		<rover-name value="Angaraka" /> <!-- Mars in Jyotish astrology (alternate name) -->
		<rover-name value="Ma'adim" /> <!-- Hebrew for "Mars" -->
		<rover-name value="al-Mirrikh" /> <!-- Arabic/Persian for "Mars" -->
		<rover-name value="Bahram" /> <!-- Ancient Persian for "Mars" -->
		<rover-name value="Merih" /> <!-- Turkish for "Mars" -->
		<rover-name value="Sakit" /> <!-- Ancient Turkish for "Mars" -->
		<rover-name value="Nergal" /> <!-- Babylonian for "Mars" -->
		<rover-name value="Areos Aster" /> <!-- Greek for "star of Ares" -->
		<rover-name value="Blodstjarna" /> <!-- Viking for "Mars" (not certain) -->
																						
	</rover-name-list>

</vehicle-configuration>
