=== mars-sim/releases/mars-sim-core/src/main/resources/conf/dtd/buildings.dtd
<!ELEMENT building-list (building*)>
<!ELEMENT building (description?, power-required, functions)>
<!ATTLIST building name CDATA #REQUIRED>
<!ATTLIST building width CDATA #REQUIRED>
<!ATTLIST building length CDATA #REQUIRED>
<!ATTLIST building base-level CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT power-required EMPTY>
<!ATTLIST power-required base-power CDATA #REQUIRED>
<!ATTLIST power-required base-power-down-power CDATA #REQUIRED>
<!ELEMENT functions (administration?, astronomical-observation?, building-connection?, 
communication?, cooking?, dining?, earth-return?, EVA?, exercise?, food-production?, farming?, 
ground-vehicle-maintenance?, life-support?, living-accommodations?, manufacture?, 
management?, medical-care?, power-generation?, power-storage?, recreation?, research?, 
resource-processing?, storage?, thermal-generation?, thermal-storage? )>
<!ELEMENT administration (activity?)>
<!ATTLIST administration population-support CDATA #REQUIRED>
<!ELEMENT astronomical-observation (activity?)>
<!ATTLIST astronomical-observation tech-level CDATA #REQUIRED>
<!ATTLIST astronomical-observation capacity CDATA #REQUIRED>
<!ATTLIST astronomical-observation power-required CDATA #REQUIRED>
<!ELEMENT building-connection EMPTY>
<!ELEMENT communication (activity?)>
<!ELEMENT cooking (activity?)>
<!ATTLIST cooking capacity CDATA #REQUIRED>
<!ELEMENT dining (activity?)>
<!ATTLIST dining capacity CDATA #REQUIRED>
<!ELEMENT earth-return EMPTY>
<!ATTLIST earth-return crew-capacity CDATA #REQUIRED>
<!ELEMENT EVA EMPTY>
<!ATTLIST EVA airlock-capacity CDATA #REQUIRED>
<!ATTLIST EVA xloc CDATA #REQUIRED>
<!ATTLIST EVA yloc CDATA #REQUIRED>
<!ATTLIST EVA interior-xloc CDATA #REQUIRED>
<!ATTLIST EVA interior-yloc CDATA #REQUIRED>
<!ATTLIST EVA exterior-xloc CDATA #REQUIRED>
<!ATTLIST EVA exterior-yloc CDATA #REQUIRED>
<!ELEMENT exercise (activity?)>
<!ATTLIST exercise capacity CDATA #REQUIRED>
<!ELEMENT farming (activity?)>
<!ATTLIST farming crops CDATA #REQUIRED>
<!ATTLIST farming power-growing-crop CDATA #REQUIRED>
<!ATTLIST farming power-sustaining-crop CDATA #REQUIRED>
<!ATTLIST farming growing-area CDATA #REQUIRED>
<!ELEMENT food-production (activity?)>
<!ATTLIST food-production tech-level CDATA #REQUIRED>
<!ATTLIST food-production concurrent-processes CDATA #REQUIRED>
<!ELEMENT ground-vehicle-maintenance (parking-location+, activity?)>
<!ATTLIST ground-vehicle-maintenance vehicle-capacity CDATA #REQUIRED>
<!ELEMENT parking-location EMPTY>
<!ATTLIST parking-location xloc CDATA #REQUIRED>
<!ATTLIST parking-location yloc CDATA #REQUIRED>
<!ELEMENT thermal-generation (heat-source+)>
<!ELEMENT heat-source EMPTY>
<!ATTLIST heat-source type CDATA #REQUIRED>
<!ATTLIST heat-source toggle (true|false) #IMPLIED>
<!ATTLIST heat-source capacity CDATA #REQUIRED>
<!ATTLIST heat-source fuel-type CDATA #IMPLIED>
<!ATTLIST heat-source consumption-rate CDATA #IMPLIED>
<!ELEMENT thermal-storage EMPTY>
<!ATTLIST thermal-storage capacity CDATA #REQUIRED>
<!ELEMENT life-support EMPTY>
<!ATTLIST life-support capacity CDATA #REQUIRED>
<!ATTLIST life-support power-required CDATA #REQUIRED>
<!ELEMENT living-accommodations (activity?)>
<!ATTLIST living-accommodations beds CDATA #REQUIRED>
<!ELEMENT management (activity?)>
<!ATTLIST management population-support CDATA #REQUIRED>
<!ELEMENT manufacture (activity?)>
<!ATTLIST manufacture tech-level CDATA #REQUIRED>
<!ATTLIST manufacture concurrent-processes CDATA #REQUIRED>
<!ELEMENT medical-care (activity?)>
<!ATTLIST medical-care tech-level CDATA #REQUIRED>
<!ATTLIST medical-care beds CDATA #REQUIRED>
<!ELEMENT power-generation (power-source+)>
<!ELEMENT power-source EMPTY>
<!ATTLIST power-source type CDATA #REQUIRED>
<!ATTLIST power-source toggle (true|false) #IMPLIED>
<!ATTLIST power-source power CDATA #REQUIRED>
<!ATTLIST power-source fuel-type CDATA #IMPLIED>
<!ATTLIST power-source consumption-rate CDATA #IMPLIED>
<!ELEMENT power-storage EMPTY>
<!ATTLIST power-storage capacity CDATA #REQUIRED>
<!ELEMENT recreation (activity?)>
<!ATTLIST recreation population-support CDATA #REQUIRED>
<!ELEMENT research (research-specialty+, activity?)>
<!ATTLIST research tech-level CDATA #REQUIRED>
<!ATTLIST research capacity CDATA #REQUIRED>
<!ELEMENT research-specialty EMPTY>
<!ATTLIST research-specialty name CDATA #REQUIRED>
<!ELEMENT resource-processing (process+, activity?)>
<!ATTLIST resource-processing power-down-level CDATA #REQUIRED>
<!ELEMENT process (input+, output+)>
<!ATTLIST process name CDATA #REQUIRED>
<!ATTLIST process power-required CDATA #REQUIRED>
<!ATTLIST process default (on|off) #REQUIRED>
<!ELEMENT input EMPTY>
<!ATTLIST input resource CDATA #REQUIRED>
<!ATTLIST input rate CDATA #REQUIRED>
<!ATTLIST input ambient (true|false) #REQUIRED>
<!ELEMENT output EMPTY>
<!ATTLIST output resource CDATA #REQUIRED>
<!ATTLIST output rate CDATA #REQUIRED>
<!ATTLIST output ambient (true|false) #REQUIRED>
<!ELEMENT storage (resource-storage+, resource-initial*)>
<!ELEMENT resource-storage EMPTY>
<!ATTLIST resource-storage resource CDATA #REQUIRED>
<!ATTLIST resource-storage capacity CDATA #REQUIRED>
<!ELEMENT resource-initial EMPTY>
<!ATTLIST resource-initial resource CDATA #REQUIRED>
<!ATTLIST resource-initial amount CDATA #REQUIRED>
<!ELEMENT activity (activity-spot+)>
<!ELEMENT activity-spot EMPTY>
<!ATTLIST activity-spot xloc CDATA #REQUIRED>
<!ATTLIST activity-spot yloc CDATA #REQUIRED>

=== mars-sim/releases/mars-sim-core/src/main/resources/conf/buildings.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE building-list SYSTEM "conf/dtd/buildings.dtd">

<!-- List of buildings that can be used in a settlement template (see settlements.xml) -->
<building-list>

	<!-- The lander hab is a general purpose habitat for 4 people. -->
	<!-- It serves as a sort of jack-of-all-trades building. -->
	<!-- name: the name of the building. -->
	<!-- width: the width of the building in meters. -->
	<!-- length: the length of the building in meters. -->
	<building name="Lander Hab" width="9.0" length="9.0">
		
		<!-- The power requirements of the building. -->
		<!-- base-power: The baseline power (kW) required by this building in 'full power' mode. -->
		<!-- base-power-down-power: the baseline power (kW) required by this building in 'power down' mode. -->
		<!-- There can be additional power requirements by the building's functions. -->
		<power-required base-power="10.0" base-power-down-power="0.0" />
		
		<!-- The functions the building is capable of performing/fulfilling. -->
		<functions>
		
			<!-- The building has communication capabilities. -->
			<communication />
			
			<!-- The building has facilities for cooking/preparing meals. -->
			<cooking capacity="1" />
		
			<!-- The building has facilities for eating meals. -->
			<dining />
		
			<!-- The building has an airlock and changing room for EVA operations. -->
			<!-- airlock-capacity: the number of people who can use the airlock at once. -->
			<EVA airlock-capacity="4" />
			
			<!-- The building has exercise facilities. -->
			<exercise capacity="1" />
		
			<!-- The building is inhabitable and can provide life support for people. -->
			<!-- capacity: number of people the building can normally support without crowding. -->
			<!-- power-required: power (kW) required for life support. -->
			<life-support capacity="4" power-required="8.0" />
		
			<!-- The building provides sleeping quarters for people. -->
			<!-- beds: the number of sleeping quarters provided. -->
			<living-accommodations beds="4" />
		
			<!-- The building has manufacturing capacity. -->
			<!-- tech-level: the technology level in manufacturing. (see tech_level.txt) -->
			<!-- concurrent-processes: the number of concurrent manufacturing processes the building 
			     can support -->
			<manufacture tech-level="1" concurrent-processes="1" />
		
			<!-- The building has a medical infirmary. -->
			<!-- tech-level: the treatment level capability of the infirmary. (see tech_level.txt) -->
			<!-- beds: the number of patients the infirmary can support. -->
			<medical-care tech-level="4" beds="2" />
		
			<!-- The building if capable of producing electrical power. -->
			<power-generation>
				<!-- A solar cell on top of the lander hab. -->
				<!-- type: the type of power source. -->
				<!-- power: the maximum power (kW) produced by the power source. -->
				<power-source type="Solar Power Source" power="5.0" />
			</power-generation>
		
			<!-- The building has recreation facilities (movies, games, music, etc.). -->
			<recreation />
		
			<!-- The building has a research laboratory. -->
			<!-- tech-level: the technology level of the lab. (see tech_level.txt) -->
			<!-- capacity: the number of researchers the lab has room for concurrently. -->
			<research tech-level="1" capacity="1">
				<!-- Sciences that can be researched at the laboratory. -->
				<research-speciality name="Areology" />
				<research-speciality name="Medicine" />
				<research-speciality name="Biology" />
				<research-speciality name="Chemistry" />
			</research>
			
			<!-- The building is capable of processing resources. -->
			<!-- power-down-level: the efficiency of the resource processes -->
			<!-- when building is in 'power down' mode. -->
			<resource-processing power-down-level=".5">
				
				<!-- Water recycling process for cleaning waste water. -->
				<process name="Water Recycling" power-required="4.0" default="off">
				
					<!-- Waste water influx. -->
					<!-- resource: the resource added to the process. -->
					<!-- See resources.xml -->
					<!-- rate: the rate (kg/sol) the resource is being added to the process. -->
					<!-- ambient: true if resource is being drown from the external environment, -->
					<!-- false if resource is being drawn from the settlement's inventory. -->
					<input resource="Waste Water" rate="100.0" ambient="false" />
					
					<!-- Clean water outflux. -->
					<!-- resource: the resource resulting from the process. -->
					<!-- See resources.xml -->
					<!-- rate: the rate (kg/sol) the resource is being produced by the process. -->
					<!-- ambient: true if resource is being released into the external environment, -->
					<!-- false if resource is stored in the settlement's inventory. -->
					<output resource="Water" rate="85.0" ambient="false" />
				</process>
				
				<!-- Carbon scrubbing process for cleaning carbon dioxide from the air. -->
				<process name="Carbon Scrubbing" power-required="2.0" default="off">
					<input resource="Carbon Dioxide" rate=".067" ambient="false" />
					<output resource="Oxygen" rate=".05" ambient="false" />
				</process>
				
			</resource-processing>
			
			<!-- The building is capable of storing resources. -->
			<storage>
			
				<!-- The building's storage capacity for oxygen. -->
				<!-- resource: the resource that the building can store. -->
				<!-- See resources.txt -->
				<!-- capacity: the building's capacity (kg) for the resource. -->
				<resource-storage resource="Oxygen" capacity="1000.0" />
				<resource-storage resource="Water" capacity="5000.0" />
				<resource-storage resource="Waste Water" capacity="500.0" />
				<resource-storage resource="Carbon Dioxide" capacity="500.0" />
				<resource-storage resource="Carbon Monoxide" capacity="50.0" />
				<resource-storage resource="Food" capacity="500.0" />
				<resource-storage resource="Ice" capacity="100.0" />
				
				<!-- The initial resources in the building. -->
				<!-- resource: the resource initially in the building. -->
				<!-- See resources.xml -->
				<!-- amount: the amount (kg) of the resource. -->
				<resource-initial resource="Water" amount="500.0" />
				<resource-initial resource="Oxygen" amount="500.0" />
				<resource-initial resource="Food" amount="500.0" /> 
			</storage>
			
		</functions>
		
	</building>
	
	<!-- The inflatable greenhouse is a small building for growing various plant crops. --> 
	<building name="Inflatable Greenhouse" width="6.0" length="9.0">
		<power-required base-power="0.0" base-power-down-power="0.0" />
		<functions>		
			
			<!-- The building is capable of growing plant crops. -->
			<!-- crops: the number of different crops grown in the building. -->
			<!-- power-growing-crop: the power (kW) required for each crop to grow an flourish. -->
			<!-- power-sustaining-crop: the minimum power (kW) required for each crop just to keep it 
			     alive. -->
			<!-- growing-area: the total area (square meters) for growing crops. -->
			<farming crops="5" power-growing-crop=".05" power-sustaining-crop=".05" growing-area="75.0" />
			
			<life-support capacity="3" power-required="6.0" />
			<research tech-level="1" capacity="1">
				<research-speciality name="Botany" />
			</research>	
			
			<resource-processing power-down-level=".5">
				<process name="Carbon Dioxide Pump" power-required="2.0" default="on">
					<input resource="Carbon Dioxide" rate="20.0" ambient="true" />
					<output resource="Carbon Dioxide" rate="20.0" ambient="false" />
				</process>
			</resource-processing>
			
			<storage>
				<resource-storage resource="Water" capacity="500.0" />
				<resource-storage resource="Waste Water" capacity="500.0" />
				<resource-storage resource="Carbon Dioxide" capacity="500.0" />
				<resource-storage resource="Food" capacity="500.0" />
			</storage>
			
		</functions>
	</building>
	
	<!-- A small, self-contained 80kW nuclear reactor that requires minimum maintenance. -->
	<building name="MD1 Nuclear Reactor" width="4.0" length="6.0">
		<power-required base-power="0.0" base-power-down-power="0.0" />
		<functions>
			<power-generation>
				<power-source type="Standard Power Source" power="80.0" />
			</power-generation>
		</functions>
	</building>
	
	<!-- A ERV (Earth Return Vehicle) base building with Sabatier chemical reactor. -->
	<!-- The starting ERV base has a full load of hydrogen and has not generated any -->
	<!-- carbon dioxide, water or oxygen yet. -->
	<building name="Starting ERV Base" width="10.0" length="10.0">
		<power-required base-power="2.0" base-power-down-power="1.0" />
		<functions>
			<power-generation>
				<power-source type="Solar Power Source" power="5.0" />
			</power-generation>
			<resource-processing power-down-level=".5">
				<process name="Sabatier" power-required="2.0" default="on">
					<input resource="Carbon Dioxide" rate="19.2" ambient="true" />
					<input resource="Hydrogen" rate="3.2" ambient="false" />
					<output resource="Methane" rate="7.2" ambient="false" />
					<output resource="Water" rate="16.0" ambient="false" />
				</process>
				<process name="Water Electrolysis" power-required="4.0" default="off">
					<input resource="Water" rate=".1" ambient="false" />
					<output resource="Hydrogen" rate=".011" ambient="false" />
					<output resource="Oxygen" rate=".089" ambient="false" />
				</process>
				<process name="CO2 Reduction" power-required="2.0" default="off">
					<input resource="Carbon Dioxide" rate=".825" ambient="true" />
					<output resource="Oxygen" rate=".3" ambient="false" />
					<output resource="Carbon Monoxide" rate=".525" ambient="false" />
				</process>
			</resource-processing>
			<storage>
				<resource-storage resource="Hydrogen" capacity="6300.0" />
				<resource-storage resource="Methane" capacity="21000.0" />
				<resource-storage resource="Oxygen" capacity="74000.0" />
				<resource-storage resource="Water" capacity="9000.0" />
