=== mars-sim/releases/mars-sim-core/src/main/resources/conf/dtd/construction.dtd
<!ELEMENT construction (foundation-list, frame-list, building-list)>
<!ELEMENT foundation-list (foundation*)>
<!ELEMENT foundation (resource*, part*, vehicle*)>
<!ATTLIST foundation name CDATA #REQUIRED>
<!ATTLIST foundation width CDATA #REQUIRED>
<!ATTLIST foundation length CDATA #REQUIRED>
<!ATTLIST foundation constructable (true|false) #REQUIRED>
<!ATTLIST foundation salvagable (true|false) #REQUIRED>
<!ATTLIST foundation work-time CDATA #REQUIRED>
<!ATTLIST foundation skill-required CDATA #REQUIRED>
<!ELEMENT resource EMPTY>
<!ATTLIST resource name CDATA #REQUIRED>
<!ATTLIST resource amount CDATA #REQUIRED>
<!ELEMENT part EMPTY>
<!ATTLIST part name CDATA #REQUIRED>
<!ATTLIST part number CDATA #REQUIRED>
<!ELEMENT vehicle (attachment-part*)>
<!ATTLIST vehicle type CDATA #REQUIRED>
<!ELEMENT attachment-part EMPTY>
<!ATTLIST attachment-part name CDATA #REQUIRED>
<!ELEMENT frame-list (frame*)>
<!ELEMENT frame (resource*, part*, vehicle*)>
<!ATTLIST frame name CDATA #REQUIRED>
<!ATTLIST frame width CDATA #REQUIRED>
<!ATTLIST frame length CDATA #REQUIRED>
<!ATTLIST frame constructable (true|false) #REQUIRED>
<!ATTLIST frame salvagable (true|false) #REQUIRED>
<!ATTLIST frame work-time CDATA #REQUIRED>
<!ATTLIST frame skill-required CDATA #REQUIRED>
<!ATTLIST frame foundation CDATA #REQUIRED>
<!ELEMENT building-list (building*)>
<!ELEMENT building (resource*, part*, vehicle*)>
<!ATTLIST building name CDATA #REQUIRED>
<!ATTLIST building width CDATA #REQUIRED>
<!ATTLIST building length CDATA #REQUIRED>
<!ATTLIST building constructable (true|false) #REQUIRED>
<!ATTLIST building salvagable (true|false) #REQUIRED>
<!ATTLIST building work-time CDATA #REQUIRED>
<!ATTLIST building skill-required CDATA #REQUIRED>
<!ATTLIST building frame CDATA #REQUIRED>

=== mars-sim/releases/mars-sim-core/src/main/resources/conf/construction.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE construction SYSTEM "conf/dtd/construction.dtd">

<construction>
	<foundation-list>

		<foundation name="surface foundation 3m x 2m" constructable="true" salvagable="true" work-time=".5" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="surface foundation 5m x 5m" constructable="true" salvagable="true" work-time="2.0" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>
	
		<foundation name="surface foundation 10m x 5m" constructable="true" salvagable="true" work-time="4.0" skill-required="1" >
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>
		
		<foundation name="subsurface foundation 5m x 5m x 3m" constructable="true" salvagable="true" work-time="20.0" skill-required="1" >
			<resource name="concrete" amount="500.0" />
			<resource name="water" amount="200.0" />
			<vehicle type="light utility vehicle" >    
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>
		
		<foundation name="unprepared surface foundation" constructable="false" salvagable="true" work-time="0.0" skill-required="0" />

	</foundation-list>

	<frame-list>
	
		<frame name="steel frame tower" constructable="true" salvagable="true" work-time="20.0" skill-required="2" foundation="surface foundation 5m x 5m" >
			<resource name="concrete" amount="50.0" />
			<resource name="water" amount="20.0" />
			<part name="steel truss" number="20" />
			<part name="steel cable" number="6" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="small steel frame" constructable="true" salvagable="true" work-time="10.0" skill-required="1" foundation="surface foundation 5m x 5m" >
			<resource name="concrete" amount="25.0" />
			<resource name="water" amount="10.0" />
			<part name="steel truss" number="10" />
			<part name="steel sheet" number="5" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
	
		<frame name="array frame" constructable="true" salvagable="true" work-time="20.0" skill-required="2" foundation="surface foundation 10m x 5m" >
			<resource name="concrete" amount="50.0" />
			<resource name="water" amount="20.0" />
			<part name="steel truss" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="brick bin frame" constructable="true" salvagable="true" work-time="5.0" skill-required="1" foundation="surface foundation 3m x 2m" >
			<resource name="mortar" amount="1680.0" />
			<resource name="water" amount="1680.0" />
			<part name="brick" number="1680" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<frame name="small brick shed frame" constructable="true" salvagable="true" work-time="40.0" skill-required="1" foundation="subsurface foundation 5m x 5m x 3m" >
			<resource name="mortar" amount="5926.0" />
			<resource name="water" amount="5926.0" />
			<part name="brick" number="5926" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>
		
		<!-- Note: the lander hab frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="lander hab frame" constructable="false" salvagable="true" work-time="200.0" skill-required="2" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="50" />
			<part name="aluminum scrap" number="50" />
			<part name="plastic pipe" number="20" />
			<part name="valve" number="10" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<part name="power cable" number="10" />
			<part name="steel pipe" number="4" />
			<part name="gasket" number="10" />
			<part name="solar panel" number="4" />
		</frame>
		
		<!-- Note: the transparant inflatable frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="transparant inflatable frame" constructable="false" salvagable="true" work-time="100.0" skill-required="2" foundation="unprepared surface foundation" >
			<part name="aluminum scrap" number="5" />
			<part name="plastic sheet" number="100" />
			<part name="plastic pipe" number="5" />
			<part name="valve" number="3" />
			<part name="gasket" number="3" />
			<part name="electrical wire" number="4" />
			<part name="wire connector" number="4" />
			<part name="power cable" number="2" />
		</frame>
		
		<!-- Note: the md1 nuclear reactor frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="md1 nuclear reactor frame" constructable="false" salvagable="true" work-time="200.0" skill-required="3" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="50" />
			<part name="steel pipe" number="10" />
			<part name="valve" number="10" />
			<part name="gasket" number="10" />
		</frame>
		
		<!-- Note: the erv base frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="erv base frame" constructable="false" salvagable="true" work-time="200.0" skill-required="2" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="50" />
			<part name="aluminum scrap" number="50" />
			<part name="plastic pipe" number="20" />
			<part name="valve" number="10" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<part name="power cable" number="10" />
			<part name="steel pipe" number="4" />
			<part name="gasket" number="10" />
			<part name="solar panel" number="4" />
		</frame>
		
		<!-- Note: the md4 nuclear reactor frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="md4 nuclear reactor frame" constructable="false" salvagable="true" work-time="400.0" skill-required="3" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="100" />
			<part name="steel pipe" number="20" />
			<part name="valve" number="20" />
			<part name="gasket" number="20" />
		</frame>
		
		<!-- Note: the atmospheric processor frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="atmospheric processor frame" constructable="false" salvagable="true" work-time="300.0" skill-required="3" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="100" />
			<part name="aluminum scrap" number="100" />
			<part name="plastic pipe" number="50" />
			<part name="valve" number="20" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="10" />
			<part name="steel pipe" number="10" />
			<part name="gasket" number="20" />
		</frame>
		
		<!-- Note: the large habitation frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="large habitation frame" constructable="false" salvagable="true" work-time="200.0" skill-required="2" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="25" />
			<part name="aluminum scrap" number="25" />
			<part name="plastic pipe" number="10" />
			<part name="valve" number="5" />
			<part name="electrical wire" number="5" />
			<part name="wire connector" number="5" />
			<part name="power cable" number="2" />
			<part name="gasket" number="4" />
		</frame>
		
		<!-- Note: the large greenhouse frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="large greenhouse frame" constructable="false" salvagable="true" work-time="300.0" skill-required="3" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="10" />
			<part name="aluminum scrap" number="15" />
			<part name="glass sheet" number="20" />
			<part name="plastic pipe" number="15" />
			<part name="valve" number="9" />
			<part name="gasket" number="9" />
			<part name="electrical wire" number="12" />
			<part name="wire connector" number="12" />
			<part name="power cable" number="6" />
		</frame>
		
		<!-- Note: the garage frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="garage frame" constructable="false" salvagable="true" work-time="200.0" skill-required="2" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="25" />
			<part name="aluminum scrap" number="25" />
			<part name="plastic pipe" number="10" />
			<part name="valve" number="5" />
			<part name="electrical wire" number="5" />
			<part name="wire connector" number="5" />
			<part name="power cable" number="2" />
			<part name="gasket" number="4" />
		</frame>
		
		<!-- Note: the observatory frame is just for salvaging and cannot be constructed insitu. -->
		<frame name="observatory frame" constructable="false" salvagable="true" work-time="200.0" skill-required="2" foundation="unprepared surface foundation" >
			<part name="steel scrap" number="25" />
			<part name="aluminum scrap" number="25" />
			<part name="plastic pipe" number="10" />
			<part name="valve" number="5" />
			<part name="electrical wire" number="5" />
			<part name="wire connector" number="5" />
			<part name="power cable" number="2" />
			<part name="gasket" number="4" />
		</frame>
		
	</frame-list>

	<building-list>

		<building name="wind turbine" constructable="true" salvagable="true" work-time="10.0" skill-required="3" frame="steel frame tower" >
