=== mars-sim/releases/mars-sim-core/src/main/resources/conf/dtd/foodProduction.dtd
<!ELEMENT foodProduction-processes (process*)>
<!ELEMENT process (description?, inputs, outputs)>
<!ATTLIST process name CDATA #REQUIRED>
<!ATTLIST process tech CDATA #REQUIRED>
<!ATTLIST process skill CDATA #REQUIRED>
<!ATTLIST process work-time CDATA #REQUIRED>
<!ATTLIST process process-time CDATA #REQUIRED>
<!ATTLIST process power-required CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT inputs (resource*, part*)>
<!ELEMENT outputs (resource*, part*, equipment*)>
<!ELEMENT resource EMPTY>
<!ATTLIST resource name CDATA #REQUIRED>
<!ATTLIST resource amount CDATA #REQUIRED>
<!ELEMENT part EMPTY>
<!ATTLIST part name CDATA #REQUIRED>
<!ATTLIST part number CDATA #REQUIRED>
<!ELEMENT equipment EMPTY>
<!ATTLIST equipment name CDATA #REQUIRED>
<!ATTLIST equipment number CDATA #REQUIRED>

=== mars-sim/releases/mars-sim-core/src/main/resources/conf/foodProduction.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE foodProduction-processes SYSTEM "conf/dtd/foodProduction.dtd">

<!-- List of all food production processes. -->
<foodProduction-processes>

	<!-- tech - The minimum tech level required to perform the process.  -->
	<!-- skill - The minimum person skill level in cooking to perform the process. -->
	<!-- work-time - The effort time (in millisols) required to perform the process.  Higher skilled workers will produce more effort time than lower skilled workers. -->
	<!-- process-time - The minimum time (in millisols) required for the process regardless of effort time. -->
	<!-- power-required - The total amount of power (kW hr) required for the process. -->
	<process name="Package Cabbage into preserved food"
			tech="1" skill="0"
			work-time="50"
			process-time="50" 
			power-required="0.1">
		<description>Cut and freeze dry cabbage into packed food.</description>
		
		<!-- List of inputs for the process (resources and parts). -->
		<inputs>
			<!-- amount - The amount of the resource in kilograms. -->
			<resource name="Cabbage" amount="5.0" />
		</inputs>
		
		<!-- List of outputs from the process (resources, parts, equipment and vehicles). -->
		<outputs>
			<resource name="food" amount="3.0" />
		</outputs>
	</process>

	<process name="Package Carrot into preserved food"
			tech="1" skill="0"
			work-time="50"
			process-time="50" 
			power-required="0.1">
		<description>Cut and freeze dry carrots into packed food.</description>	
		<inputs>
			<resource name="Carrot" amount="5.0" />
		</inputs>	
		<outputs>
			<resource name="food" amount="3.0" />
		</outputs>
	</process>
	
	<process name="Package Swiss Chard into preserved food"
			tech="1" skill="0"
			work-time="50"
			process-time="50" 
			power-required="0.1">
		<description>Cut and freeze dry swiss chard into packed food.</description>	
		<inputs>
			<resource name="Swiss Chard" amount="5.0" />
		</inputs>	
		<outputs>
			<resource name="food" amount="3.0" />
		</outputs>
	</process>
	
	<process name="Package potatoes into preserved food"
			tech="1" skill="0"
			work-time="50"
			process-time="50" 
			power-required="0.1">
		<description>Cut and dry potatoes into packed food.</description>	
		<inputs>
			<resource name="Potato" amount="10.0" />
		</inputs>	
		<outputs>
			<resource name="food" amount="5.0" />
		</outputs>
	</process>
	
	<process name="Package Quinoa into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100" 
			power-required="0.1">
		<description>Package puffed Quinoa, honey, nuts and dried fruits into Granola Bar.</description>	
		<inputs>
			<resource name="Quinoa" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Honey" amount="0.5" />
			<resource name="Peanut" amount="1.0" />
		</inputs>	
		<outputs>
			<resource name="Granola Bar" amount="4.0" />
		</outputs>
	</process>

	<process name="Package Rice into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100" 
			power-required="0.1">
		<description>Package puffed rice, honey, nuts and dried fruits into Granola Bar.</description>	
		<inputs>
			<resource name="Rice" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Honey" amount="0.5" />
			<resource name="Peanut" amount="1.0" />			
		</inputs>	
		<outputs>
			<resource name="Granola Bar" amount="4.0" />
		</outputs>
	</process>
	
		<process name="Package Wheat into Granola Bar"
			tech="1" skill="0"
			work-time="50"
			process-time="100" 
			power-required="0.1">
		<description>Package puffed wheat, honey, nuts and dried fruits into Granola Bar.</description>	
		<inputs>
			<resource name="Wheat" amount="4.0" />
			<resource name="Strawberry" amount="0.5" />
			<resource name="Honey" amount="0.5" />
			<resource name="Peanut" amount="1.0" />		
		</inputs>	
		<outputs>
			<resource name="Granola Bar" amount="4.0" />
		</outputs>
	</process>
	
	<process name="Make French Fries from potatoes"
			tech="1" skill="1"
			work-time="50"
			process-time="50" 
			power-required="0.7">
		<description>Cut potatoes and make French Fries.</description>	
		<inputs>
			<resource name="Potato" amount="10.0" />
			<resource name="Peanut Oil" amount="1.0" />
		</inputs>	
		<outputs>
			<resource name="French Fries" amount="10.0" />
		</outputs>
	</process>
	
	<process name="Make Soy Sprouts from Soybeans"
			tech="1" skill="1"
			work-time="50"
			process-time="3000" 
			power-required="0.0">
		<description>Sanitize soybean seeds with sodium hypochlorite. Wash the seeds and soak them in water and 
			wait for germination. When germinated, freeze dry them. </description>	
		<inputs>
			<resource name="Soybean" amount="3.0" />
			<resource name="Water" amount="3.0" />
			<resource name="Sodium Hypochlorite" amount="0.1" />
		</inputs>
		
		<outputs>
			<resource name="Soy Sprout" amount="15.0" />
		</outputs>
	</process>
	
		<process name="Make Quinoa Sprouts from Quinoa"
			tech="1" skill="1"
			work-time="50"
			process-time="2000" 
			power-required="0.0">
		<description>Rinse the quinoa seeds in a bowl. Wash the quinoa seeds to remove the soapy coating known as saponin. 
			Soak in water and drain the water after 30 minutes. Repeat the rinsing and draining process every 8 hours. Put the tray of quinoa in a dark room. Place the cloth back over the quinoa for protection. 
			The quinoa will sprout into a plate full of spiral-shaped roots that are at least one-quarter inch in length. 
			Dry out sprouts for up to 12 hours after fully germinated. </description>	
		<inputs>
			<resource name="Quinoa" amount="3.0" />
			<resource name="Water" amount="3.0" />
		</inputs>
		
		<outputs>
			<resource name="Quinoa Sprout" amount="15.0" />
		</outputs>
	</process>
	
	<process name="Make Okara and Soymilk from Soybeans" 
		tech="1" skill="1" work-time="60" process-time="700" 
			power-required="1.0">
			
		<description> Make pulp (Okara) and Soymilk from Soybean after 
			Washing, Dehulling, Soaking, Milling, Paste 
			Heating, and Filtration. </description>
		<inputs>
			<!--<equipment name="oven" number="1" />-->
			<resource name="Soybean" amount="1.0" />
			<resource name="Water" amount="16.0" />
			<resource name="Sugar" amount="0.1" />			
		</inputs>
		<outputs>
			<resource name="Okara" amount="0.8" />
			<resource name="Soymilk" amount="12.0" />
		</outputs>
	</process>
	
	
	<process name="Press and refine Peanut Oil from Peanuts" 
		tech="2" skill="2" work-time="50" process-time="400" 
			power-required="2.0">
			
		<description>Derive vegetableâ€…oil from peanuts. Press and refine it
			for use </description>
		
		<inputs>
			<!--<equipment name="oven" number="1" />-->
			<resource name="Peanut" amount="4.0" />
		</inputs>
		<outputs>
			<resource name="Peanut Oil" amount="2.0" />
		</outputs>
	</process>
	
	<process name="Chop and Roast Peanuts in Oven" 
		tech="1" skill="1" work-time="50" process-time="300" 
			power-required="1.0">
			
		<description>Chopped up peanuts and roast them in oven </description>
		
		<inputs>
			<!--<equipment name="oven" number="1" />-->
			<resource name="Peanut" amount="5.0" />
			<resource name="Table Salt" amount="0.5" />
		</inputs>
		<outputs>
			<resource name="Roasted Peanut" amount="5.0" />
		</outputs>
	</process>
	
		<process name="Make Peanut Butter from Peanuts" 
		tech="1" skill="1" work-time="50" process-time="50" 
			power-required="0.2">
			
		<description>Ground peanuts, mix with oil, pour the mixture into food processor.
		Blend until smooth.</description>
		
		<inputs>
			<!--<equipment name="oven" number="1" 
			TODO: add cocoa powder, cinnamon or other spice
			/>-->
			<resource name="Peanut" amount="3.0" />
			<resource name="Soybean Oil" amount="0.5" />
			<resource name="Table Salt" amount="0.1" />
			<resource name="Soy Protein" amount="0.1" />
		</inputs>
		<outputs>
			<resource name="Peanut Butter" amount="3.5" />
		</outputs>
	</process>
	
	
	<process name="Package Roast Peanuts into dry food " 
		tech="0" skill="0" work-time="50" process-time="50" 
			power-required="1.0">
			
		<description>Pack peanuts into dry food</description>
		
		<inputs>
			<!--<equipment name="oven" number="1" />-->
			<resource name="Roasted Peanut" amount="5.0" />
		</inputs>
		<outputs>
			<resource name="food" amount="5.0" />
		</outputs>
	</process>
	
	
	<process name="Bake White Bread from Soy Flour " 
		tech="1" skill="2" work-time="50" process-time="200" 
			power-required="1.0">
			
		<description> Make 2 loaves of White Bread from Soy Flour </description>
		
		<inputs>
			<!-- <equipment name="oven" number="1" /> -->
			<resource name="Soy Flour" amount="1.0" />
			<resource name="Water" amount="0.33" />
			<resource name="Yeast" amount="0.01" />			
		</inputs>
		<outputs>
			<resource name="White Bread" amount="1.2" />
		</outputs>
	</process>
	
	<process name="Make Tofu from Okara and Soymilk" 
		tech="1" skill="2" work-time="50" process-time="500" 
			power-required="1.0">
			
		<description> Boil up Okara-Soymilk mixture, add Epsom Salt as Coagulants, 
			gently stir and heat, the curds will separate.</description>
		
		<inputs>
			<resource name="Soymilk" amount="3.0" />
			<resource name="Okara" amount="0.5" />
			<resource name="Epsom Salt" amount=".05" />			
		</inputs>
		<outputs>
			<resource name="Tofu" amount="2.0" />			
		</outputs>
	</process>
	
	
	<process name="Process Soybean into Soy Flour" 
		tech="1" skill="2" work-time="50" process-time="400" 
			power-required="5.0">
		<description> Create Defatted Soy Flour by Cracking, Screening, Heating Soybean at 130 deg C with Hot Extrusion and Pressure at 40-60 MPa.  </description>
		<inputs>
			<!--<equipment name="oven" number="1" />-->
			<resource name="Soybean" amount="1.0" />
			<resource name="Water" amount="5.0" />
		</inputs>
		<outputs>
			<resource name="Soy Flour" amount="1.0" />
		</outputs>
	</process>

	
	<process name= "Process White Rice into Rice Flour"
