=== mars-sim/releases/mars-sim-core/src/main/resources/conf/dtd/manufacturing.dtd
<!ELEMENT manufacturing-processes (process*, salvage*)>
<!ELEMENT process (inputs, outputs)>
<!ATTLIST process name CDATA #REQUIRED>
<!ATTLIST process tech CDATA #REQUIRED>
<!ATTLIST process skill CDATA #REQUIRED>
<!ATTLIST process work-time CDATA #REQUIRED>
<!ATTLIST process process-time CDATA #REQUIRED>
<!ATTLIST process power-required CDATA #REQUIRED>
<!ELEMENT inputs (resource*, part*)>
<!ELEMENT outputs (resource*, part*, equipment*, vehicle*)>
<!ELEMENT resource EMPTY>
<!ATTLIST resource name CDATA #REQUIRED>
<!ATTLIST resource amount CDATA #REQUIRED>
<!ELEMENT part EMPTY>
<!ATTLIST part name CDATA #REQUIRED>
<!ATTLIST part number CDATA #REQUIRED>
<!ELEMENT equipment EMPTY>
<!ATTLIST equipment name CDATA #REQUIRED>
<!ATTLIST equipment number CDATA #REQUIRED>
<!ELEMENT vehicle EMPTY>
<!ATTLIST vehicle name CDATA #REQUIRED>
<!ATTLIST vehicle number CDATA #REQUIRED>
<!ELEMENT salvage (part-salvage*)>
<!ATTLIST salvage item-name CDATA #REQUIRED>
<!ATTLIST salvage type (equipment|vehicle) #REQUIRED>
<!ATTLIST salvage tech CDATA #REQUIRED>
<!ATTLIST salvage skill CDATA #REQUIRED>
<!ATTLIST salvage work-time CDATA #REQUIRED>
<!ELEMENT part-salvage EMPTY>
<!ATTLIST part-salvage name CDATA #REQUIRED>
<!ATTLIST part-salvage number CDATA #REQUIRED>

=== mars-sim/releases/mars-sim-core/src/main/resources/conf/manufacturing.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE manufacturing-processes SYSTEM "conf/dtd/manufacturing.dtd">

<!-- List of all manufacturing processes. -->
<manufacturing-processes>

	<!-- tech - The minimum workshop tech level required to perform the process. (see tech_level.txt) -->
	<!-- skill - The minimum person skill level in materials science to perform the process. -->
	<!-- work-time - The effort time (in millisols) required to perform the process.  Higher skilled -->
	<!--             workers will produce more effort time than lower skilled workers. -->
	<!-- process-time - The minimum time (in millisols) required for the process regardless of effort time. -->
	<!-- power-required - The total amount of power (kW hr) required for the process. -->
	<process name="extract iron oxide from regolith"
			tech="1" skill="0"
			work-time="100"
			process-time="0" 
			power-required="0.0">
		<description>Process for extracting iron oxide from regolith.</description>
		
		<!-- List of inputs for the process (resources and parts). -->
		<inputs>
		
			<!-- amount - The amount of the resource in kilograms. -->
			<resource name="regolith" amount="50.0" />
		</inputs>
		
		<!-- List of outputs from the process (resources, parts, equipment and vehicles). -->
		<outputs>
			<resource name="iron oxide" amount="7.0" />
			<resource name="sand" amount="40.0" />
		</outputs>
	</process>
	
	<process name="extract iron oxide from regolith (large batch)"
			tech="1" skill="2"
			work-time="500"
			process-time="0" 
			power-required="0.0">
		<inputs>
			<resource name="regolith" amount="500.0" />
		</inputs>
		<outputs>
			<resource name="iron oxide" amount="70.0" />
			<resource name="sand" amount="400.0" />
		</outputs>
	</process>
	
	<process name="extract aluminum oxide from regolith"
			tech="1" skill="0"
			work-time="100"
			process-time="0"
			power-required="0.0">
		<inputs>
			<resource name="regolith" amount="50.0" />
		</inputs>
		<outputs>
			<resource name="aluminum oxide" amount="2.0" />
		</outputs>
	</process>
	
	<process name="extract aluminum oxide from regolith (large batch)" tech="1" skill="2" work-time="500" process-time="0"
			power-required="0.0">
		<inputs>
			<resource name="regolith" amount="500.0" />
		</inputs>
		<outputs>
			<resource name="aluminum oxide" amount="20.0" />
		</outputs>
	</process>
	
	<process name="extract aluminum oxide from sand" tech="1" skill="0" work-time="100" process-time="0" 
			power-required="0.0">
		<inputs>
			<resource name="sand" amount="50.0" />
		</inputs>
		<outputs>
			<resource name="aluminum oxide" amount="2.0" />
		</outputs>
	</process>
	
	<process name="extract aluminum oxide from sand (large batch)" tech="1" skill="2" work-time="500" process-time="0" 
			power-required="0.0">
		<inputs>
			<resource name="sand" amount="500.0" />
		</inputs>
		<outputs>
			<resource name="aluminum oxide" amount="20.0" />
		</outputs>
	</process>
	
	<process name="carbon monoxide iron reduction"
			tech="1" skill="1"
			work-time="50"
			process-time="200"
			power-required="2.0">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3CO -> 2Fe + 3CO&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="iron oxide" amount="50.0" />
			<resource name="carbon monoxide" amount="26.4" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="34.9" />
			<resource name="carbon dioxide" amount="41.3" />
		</outputs>
	</process>
	
	<process name="carbon monoxide iron reduction (large batch)"
			tech="1" skill="3"
			work-time="250"
			process-time="1000"
			power-required="2.0">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3CO -> 2Fe + 3CO&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="iron oxide" amount="500.0" />
			<resource name="carbon monoxide" amount="264.0" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="349.0" />
			<resource name="carbon dioxide" amount="413.0" />
		</outputs>
	</process>
	
	<process name="hydrogen iron reduction"
			tech="1" skill="1"
			work-time="50"
			process-time="200" 
			power-required="2.0">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3H&lt;sub&gt;2&lt;/sub&gt; -> 2Fe + 3H&lt;sub&gt;2&lt;/sub&gt;O</description>
		<inputs>
			<resource name="iron oxide" amount="50.0" />
			<resource name="hydrogen" amount="2.5" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="34.9" />
			<resource name="water" amount="16.9" />
		</outputs>
	</process>
	
	<process name="hydrogen iron reduction (large batch)"
			tech="1" skill="3"
			work-time="250"
			process-time="1000" 
			power-required="2.0">
		<description>Fe&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3H&lt;sub&gt;2&lt;/sub&gt; -> 2Fe + 3H&lt;sub&gt;2&lt;/sub&gt;O</description>
		<inputs>
			<resource name="iron oxide" amount="500.0" />
			<resource name="hydrogen" amount="25.0" />
		</inputs>
		<outputs>
			<resource name="iron powder" amount="349.0" />
			<resource name="water" amount="169.0" />
		</outputs>
	</process>
	
	<!-- Produces 5 5kg iron ingots. -->
	<process name="iron ingot casting" tech="2" skill="2" work-time="100" process-time="200" 
			power-required="5.0">
		<inputs>
			<resource name="iron powder" amount="25.0" />
		</inputs>
		<outputs>
			<part name="iron ingot" number="5" />
		</outputs>
	</process>
	
	<!-- Produces 50 5kg iron ingots. -->
	<process name="iron ingot casting (large batch)" tech="2" skill="4" work-time="500" process-time="1000" 
			power-required="5.0">
		<inputs>
			<resource name="iron powder" amount="250.0" />
		</inputs>
		<outputs>
			<part name="iron ingot" number="50" />
		</outputs>
	</process>
	
	<!-- Produces 1m x 2m x 1mm (15kg) sheet of iron. -->
	<process name="iron sheet manufacturing" tech="2" skill="2" work-time="200" process-time="200" 
			power-required="7.0">
		<inputs>
			<resource name="iron powder" amount="15.0" />
		</inputs>
		<outputs>
			<part name="iron sheet" number="1" />
		</outputs>
	</process>
	
	<!-- Produces 1m x 2m x 1mm (15kg) sheet of iron. -->
	<process name="iron sheet rolling" tech="2" skill="2" work-time="200" process-time="200" 
			power-required="5.0">
		<inputs>
			<part name="iron ingot" number="3" />
		</inputs>
		<outputs>
			<part name="iron sheet" number="1" />
		</outputs>
	</process>
	
	<!-- Produces 5 1kg aluminum ingots. -->
	<process name="aluminum ingot casting"
			tech="2" skill="2"
			work-time="100"
			process-time="200" 
			power-required="20.0">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO</description>
		<inputs>
			<resource name="aluminum oxide" amount="9.5" />
			<resource name="carbon" amount="3.0" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="7.5" />
			<part name="aluminum ingot" number="5" />
		</outputs>
	</process>
	
	<!-- Produces 50 1kg aluminum ingots. -->
	<process name="aluminum ingot casting (large batch)" tech="2" skill="4" work-time="500" process-time="1000" 
			power-required="20.0">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO</description>
		<inputs>
			<resource name="aluminum oxide" amount="95.0" />
			<resource name="carbon" amount="30.0" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="75.0" />
			<part name="aluminum ingot" number="50" />
		</outputs>
	</process>
	
	<!-- Produces 1m x 2m x 1mm (5kg) sheet of aluminum. -->
	<process name="aluminum sheet manufacturing" tech="2" skill="2" work-time="200" process-time="200" 
			power-required="25.0">
		<description>Al&lt;sub&gt;2&lt;/sub&gt;O&lt;sub&gt;3&lt;/sub&gt; + 3C -> 2Al + 3CO</description>
		<inputs>
			<resource name="aluminum oxide" amount="9.5" />
			<resource name="carbon" amount="3.0" />
		</inputs>
		<outputs>
			<resource name="carbon monoxide" amount="7.5" />
			<part name="aluminum sheet" number="1" />
		</outputs>
	</process>
	
	<!-- Produces 1m x 2m x 1mm (5kg) sheet of aluminum. -->
	<process name="aluminum sheet rolling" tech="2" skill="2" work-time="200" process-time="200" 
			power-required="5.0">
		<inputs>
			<part name="aluminum ingot" number="5" />
		</inputs>
		<outputs>
			<part name="aluminum sheet" number="1" />
		</outputs>
	</process>
	
	<!-- Produces 1kg spool of thin aluminum wire. -->
	<process name="aluminum wire drawing" tech="2" skill="3" work-time="300" process-time="200" 
			power-required="7.0">
		<inputs>
			<part name="aluminum sheet" number="1" />
		</inputs>
		<outputs>
			<part name="aluminum wire" number="5" />
		</outputs>
	</process>
	
	<process name="pyrolyze reaction" tech="1" skill="1" work-time="25" process-time="200" 
			power-required="0.5">
		<description>CH&lt;sub&gt;4&lt;/sub&gt; -> C + 2H&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="methane" amount="1.3" />
		</inputs>
		<outputs>
			<resource name="carbon" amount="1.0" />
			<resource name="hydrogen" amount=".3" />
		</outputs>
	</process>
	
	<process name="advanced pyrolyze reaction" tech="2" skill="2" work-time="50" process-time="400" 
			power-required="5.0">
		<description>CH&lt;sub&gt;4&lt;/sub&gt; -> C + 2H&lt;sub&gt;2&lt;/sub&gt;</description>
		<inputs>
			<resource name="methane" amount="13.0" />
		</inputs>
		<outputs>
			<resource name="carbon" amount="10.0" />
			<resource name="hydrogen" amount="3.0" />
		</outputs>
	</process>
	
	<!-- Produces 5 5kg steel ingots. -->
	<process name="steel ingot alloying" tech="2" skill="3" work-time="100" process-time="100" 
			power-required="10.0">
		<inputs>
			<resource name="iron powder" amount="25.0" />
			<resource name="carbon" amount=".5" />
		</inputs>
		<outputs>
			<part name="steel ingot" number="5" />
		</outputs>
	</process>
	
	<!-- Produces 50 5kg steel ingots. -->
	<process name="steel ingot alloying" tech="2" skill="5" work-time="500" process-time="500" 
			power-required="10.0">
		<inputs>
			<resource name="iron powder" amount="250.0" />
