=== mars-sim/releases/mars-sim-core/src/main/resources/conf/dtd/parts.dtd
<!ELEMENT part-list (part*)>
<!ELEMENT part (description?,maintenance-entity-list?)>
<!ATTLIST part name CDATA #REQUIRED>
<!ATTLIST part mass CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT maintenance-entity-list (entity*)>
<!ELEMENT entity EMPTY>
<!ATTLIST entity name CDATA #REQUIRED>
<!ATTLIST entity probability CDATA #REQUIRED>
<!ATTLIST entity max-number CDATA #REQUIRED>

=== mars-sim/releases/mars-sim-core/src/main/resources/conf/parts.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE part-list SYSTEM "conf/dtd/parts.dtd">

<part-list>
	<part name="airleak patch" mass=".2">
		<description>Plastic and adhesive patch for airleaks.</description>
		<maintenance-entity-list>
			<entity name="life support" probability="10" max-number="4" />
			<entity name="rover" probability="10" max-number="2" />
			<entity name="eva suit" probability="10" max-number="1" />
			<entity name="farming" probability="10" max-number="4" />
		</maintenance-entity-list>
	</part>
	<part name="co2 extinguisher" mass="20.0" />
	<part name="rover wheel" mass="50.0">
		<description>Rover wheels are made of steel and steel wire.</description>
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="6" />
		</maintenance-entity-list>
	</part>
	<part name="gasket" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="30" max-number="4" />
			<entity name="farming" probability="60" max-number="6" />
			<entity name="living accomodations" probability="30" max-number="4" />
			<entity name="manufacture" probability="60" max-number="6" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="15" max-number="2" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="valve" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="20" max-number="2" />
			<entity name="farming" probability="30" max-number="3" />
			<entity name="living accomodations" probability="15" max-number="2" />
			<entity name="manufacture" probability="30" max-number="3" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="10" max-number="1" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="epoxy resin bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="50" max-number="6" />
			<entity name="farming" probability="80" max-number="12" />
			<entity name="living accomodations" probability="40" max-number="4" />
			<entity name="manufacture" probability="80" max-number="6" />
			<entity name="eva suit" probability="20" max-number="1" />
			<entity name="settlement" probability="20" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<part name="spark plug" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="30" max-number="2" />
		</maintenance-entity-list>
	</part>
	
	<part name="coolant bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="30" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="electrical wire" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="30" max-number="6" />
			<entity name="power generation" probability="20" max-number="4" />
			<entity name="manufacture" probability="20" max-number="4" />
			<entity name="settlement" probability="10" max-number="8" />
		</maintenance-entity-list>
	</part>
	
	<part name="power cable" mass="2.0">
		<maintenance-entity-list>
			<entity name="power generation" probability="10" max-number="2" />
			<entity name="settlement" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<part name="wire connector" mass=".1">
		<maintenance-entity-list>
			<entity name="vehicle" probability="30" max-number="6" />
			<entity name="power generation" probability="20" max-number="4" />
			<entity name="manufacture" probability="20" max-number="4" />
			<entity name="settlement" probability="10" max-number="8" />
		</maintenance-entity-list>
	</part>
	
	<part name="plastic tubing" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="10" max-number="4" />
			<entity name="farming" probability="30" max-number="10" />
			<entity name="manufacture" probability="60" max-number="10" />
			<entity name="settlement" probability="10" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<part name="lubricant bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="10" max-number="4" />
			<entity name="manufacture" probability="10" max-number="2" />
		</maintenance-entity-list>
	</part>
	
	<part name="rover battery" mass="50.0">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="light utility vehicle" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="radio antenna" mass="2.0">
		<maintenance-entity-list>
			<entity name="vehicle" probability="10" max-number="1" />
			<entity name="communication" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="satellite dish" mass="10.0">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="timing belt" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="30" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="communications circuit board" mass=".5">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="navigation circuit board" mass=".5">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="suit heating unit" mass="2.0">
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="plastic pipe" mass="1.0">
		<maintenance-entity-list>
			<entity name="living accomodations" probability="10" max-number="2" />
			<entity name="farming" probability="20" max-number="4" />
			<entity name="manufacture" probability="20" max-number="2" />
			<entity name="rover" probability="5" max-number="1" />
			<entity name="settlement" probability="10" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<part name="steel pipe" mass="10.0">
		<maintenance-entity-list>
			<entity name="farming" probability="10" max-number="2" />
			<entity name="manufacture" probability="10" max-number="2" />
			<entity name="rover" probability="10" max-number="1" />
			<entity name="settlement" probability="10" max-number="2" />
		</maintenance-entity-list>
	</part>
	
	<part name="iron pipe" mass="10.0">
		<maintenance-entity-list>
			<entity name="farming" probability="10" max-number="2" />
			<entity name="manufacture" probability="10" max-number="2" />
			<entity name="rover" probability="10" max-number="1" />
			<entity name="settlement" probability="10" max-number="2" />
		</maintenance-entity-list>
	</part>
	
	<part name="copper pipe" mass="5.0">
		<maintenance-entity-list>
			<entity name="living accomodations" probability="10" max-number="1" />
			<entity name="farming" probability="20" max-number="2" />
			<entity name="manufacture" probability="10" max-number="2" />
			<entity name="settlement" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="iron ingot" mass="5.0" />
	
	<part name="steel ingot" mass="5.0" />
	
	<part name="aluminum ingot" mass="1.0" />
	
	<part name="steel canister" mass="10.0" />
	
	<part name="bottle" mass=".1" />
	
	<part name="steel sheet" mass="15.0">
		<description>1m x 2m x 1mm sheet of steel</description>
	</part>
	
	<!-- 1m x 2m x 1mm sheet of iron -->
	<part name="iron sheet" mass="15.0" />
	
	<!-- 1m x 2m x 1mm sheet of aluminum -->
	<part name="aluminum sheet" mass="5.0" />
	
	<!-- 1kg spool of thick steel wire -->
	<part name="steel wire" mass="1.0" />
	
	<!-- 5kg spool of thick steel cable -->
	<part name="steel cable" mass="5.0" />
	
	<!-- 1kg spool of thin aluminum wire -->
	<part name="aluminum wire" mass="1.0" />
	
	<!-- 1kg spool of thin fiberglass -->
	<part name="fiberglass" mass="1.0" />
	
	<!-- 1m x 1m square of woven fiberglass cloth -->
	<part name="fiberglass cloth" mass=".1" />
	
	<!-- 1m x 1m square of thin plastic sheet -->
	<part name="plastic sheet" mass=".1" />
	
	<!-- 1m x 1m x 1cm square of glass  -->
	<part name="glass sheet" mass="26.0" />
	
	<part name="eva helmet" mass="2.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="helmet visor" mass="2.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="counter pressure suit" mass="1.0" >
		<description>Spandex inner EVA suit for counter pressure.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="coveralls" mass="2.0" >
		<description>Outer EVA suit with insulative liner.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="eva gloves" mass="1.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="eva boots" mass="4.0" >
		<description>steel soled and tipped.  Fiberglass insulated.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="eva pads" mass="2.0" >
		<description>steel plate with fiberglass insulation.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="10" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="eva backpack" mass="15.0" >
		<description>made with polyethylene and a steel frame.</description>
