=== mars-sim/releases/mars-sim-core/src/main/resources/conf/dtd/resupplies.dtd
<!ELEMENT resupply-list (resupply*)>
<!ELEMENT resupply (building*, vehicle*, equipment*, person?, resource*, part*, part-package*)>
<!ATTLIST resupply name CDATA #REQUIRED>
<!ELEMENT building EMPTY>
<!ATTLIST building type CDATA #REQUIRED>
<!ATTLIST building width CDATA #IMPLIED>
<!ATTLIST building length CDATA #IMPLIED>
<!ATTLIST building x-location CDATA #REQUIRED>
<!ATTLIST building y-location CDATA #REQUIRED>
<!ATTLIST building facing CDATA #REQUIRED>
<!ELEMENT vehicle EMPTY>
<!ATTLIST vehicle type CDATA #REQUIRED>
<!ATTLIST vehicle number CDATA #REQUIRED>
<!ELEMENT equipment EMPTY>
<!ATTLIST equipment type CDATA #REQUIRED>
<!ATTLIST equipment number CDATA #REQUIRED>
<!ELEMENT person EMPTY>
<!ATTLIST person number CDATA #REQUIRED>
<!ELEMENT resource EMPTY>
<!ATTLIST resource type CDATA #REQUIRED>
<!ATTLIST resource amount CDATA #REQUIRED>
<!ELEMENT part EMPTY>
<!ATTLIST part type CDATA #REQUIRED>
<!ATTLIST part number CDATA #REQUIRED>
<!ELEMENT part-package EMPTY>
<!ATTLIST part-package name CDATA #REQUIRED>
<!ATTLIST part-package number CDATA #REQUIRED>

=== mars-sim/releases/mars-sim-core/src/main/resources/conf/resupplies.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE resupply-list SYSTEM "conf/dtd/resupplies.dtd">

<!-- Settlement resupply missions from Earth. -->
<resupply-list>

	<!-- Resupply mission from Earth. -->
	<!-- name: the unique name of the resupply mission. -->
	<resupply name="Mars Direct Base resupply 1">
	
		<!-- A new building for the settlement. -->
		<!-- type: the type of building (see buildings.xml) -->
		<!-- number: the number of these buildings provided. -->
		<building type="Lander Hab" number="1" />
		
		<building type="Inflatable Greenhouse" number="1" />
		<building type="MD1 Nuclear Reactor" number="1" />
		<building type="Starting ERV Base" number="1" />
		
		<!-- New equipment -->
		<!-- type: the type of equipment. -->
		<!-- number: the number of this type of equipment. -->
		<equipment type="EVA Suit" number="8" />
		<equipment type="Gas Canister" number="10" />
		<equipment type="Bag" number="10" />
		<equipment type="Large Bag" number="10" />
		<equipment type="Barrel" number="10" />
		
		<!-- New immigrants from Earth. -->
		<!-- number: the number of immigrants. -->
		<person number="4" />
		
		<!-- Resource provided in this resupply. -->
		<!-- type: the type of resource (see resources.txt) -->
		<!-- amount: the amount of the resource (kg) -->
		<resource type="hydrogen" amount="1000.0" />
		<resource type="food" amount="500.0" />
			
		<!-- Part packages (see part_packages.xml) -->
		<!-- name: the part package name. -->
		<!-- number: the number of packages. -->
		<part-package name="package 2" number="1" />
			
	</resupply>
		
	<resupply name="Mars Direct Base resupply 2">
		<building type="Lander Hab" number="1" />
		<building type="Inflatable Greenhouse" number="1" />
		<building type="MD1 Nuclear Reactor" number="1" />
		<building type="Starting ERV Base" number="1" />
		<vehicle type="Explorer Rover" number="1" />
		<vehicle type="Transport Rover" number="1" />
		<vehicle type="Light Utility Vehicle" number="1" />
		<equipment type="EVA Suit" number="8" />
		<equipment type="Gas Canister" number="10" />
		<equipment type="Barrel" number="10" />
		<equipment type="Bag" number="20" />
		<equipment type="Large Bag" number="10" />
		<equipment type="Specimen Box" number="20" />
		<person number="4" />
		<resource type="hydrogen" amount="1000.0" />
		<resource type="food" amount="500.0" />
		<part-package name="package 3" number="1" />
	</resupply>
		
	<resupply name="Mars Direct Base resupply 3">
		<building type="Atmospheric Processor" number="1" />
		<building type="Residential Quarters" number="1" />
		<building type="Lounge" number="1" />
		<building type="Infirmary" number="1" />
		<building type="Command and Control" number="1" />
		<building type="Large Greenhouse" number="1" />
		<building type="Laboratory" number="1" />
		<building type="Garage" number="1" />
		<building type="Workshop" number="1" />
		<building type="MD4 Nuclear Reactor" number="2" />
		<building type="Astronomy Observatory" number="1" />
		<vehicle type="Explorer Rover" number="2" />
		<vehicle type="Transport Rover" number="2" />
		<vehicle type="Light Utility Vehicle" number="1" />
		<equipment type="EVA Suit" number="24" />
		<equipment type="Gas Canister" number="10" />
		<equipment type="Barrel" number="10" />
		<equipment type="Bag" number="40" />
		<equipment type="Large Bag" number="10" />
		<equipment type="Specimen Box" number="40" />
		<person number="12" />
		<resource type="hydrogen" amount="1000.0" />
		<resource type="food" amount="500.0" />
		<part-package name="package 4" number="1" />
	</resupply>
	
</resupply-list>
